/** Hydraulic Parts catalog seed — Parts Village. */
import type { Part } from "@/lib/mock-data";

export const hydraulicParts: Part[] = [
  {
    id: "hydraulic-hpv116-cp-hd",
    partNumber: "HPV116-CP-HD",
    partNumbers: [
      "HPV116-CP-HD",
      "HPV116-CENTER-PIN",
      "71402440",
      "9065880",
      "9065882",
      "TH109461",
      "HD-HPV116-CP",
    ],
    name: "Handok HPV116 Hydraulic Pump Center Piston (Cylinder Guide Hub)",
    description:
      "Handok Hydraulic (South Korea) · HPV116 center piston / cylinder guide hub · High-density hardened carbon steel · Precision ground & polished · Pump displacement 116cc / 118cc",
    category: "Hydraulic Parts",
    quantity: 10,
    reorderAt: 2,
    cost: 0,
    price: 0,
    compatibility: [
      "Fiat Hitachi EX215",
      "Fiat Hitachi EX200-1",
      "Fiat Hitachi EX220-1",
      "Fiat Hitachi FH200",
      "Fiat Hitachi FH220",
      "Fiat Kobelco EX215",
      "Fiat Kobelco EX200-1",
      "Fiat Kobelco EX220-1",
      "Fiat Kobelco FH200",
      "Fiat Kobelco FH220",
      "Hitachi EX200-1",
      "Hitachi EX220-1",
      "Hitachi ZX200",
      "Hitachi ZX200-3",
      "Hitachi ZX210-3",
      "Hitachi ZX240-3",
      "Hitachi ZX270-3",
      "John Deere 200CLC",
      "John Deere 240D",
      "John Deere 270CLC",
    ],
    notes:
      "Manufacturer: Handok Hydraulic (South Korea) · Material: high-density hardened carbon steel · Surface: precision ground & polished to OEM micro-tolerances · Pump displacement 116cc / 118cc · OEM xref: HPV116-CENTER-PIN, 71402440, 9065880, 9065882, TH109461, HD-HPV116-CP · Fitment: Fiat Hitachi/Kobelco main pump group; Hitachi rotary group central piston; John Deere main hydraulic cylinder barrel guide pin",
  },
  {
    id: "hydraulic-hpv145-cp-hd",
    partNumber: "HPV145-CP-HD",
    partNumbers: [
      "HPV145-CP-HD",
      "HPV145-CENTER-PIN",
      "3081023",
      "4243645",
      "71402450",
      "HD-HPV145-CP",
    ],
    name: "Handok HPV145 Hydraulic Pump Center Piston (Cylinder Guide Hub)",
    description:
      "Handok Hydraulic (South Korea) · HPV145 center piston / cylinder guide hub · High-density hardened carbon steel · Precision ground & polished · Pump displacement 145cc",
    category: "Hydraulic Parts",
    quantity: 10,
    reorderAt: 2,
    cost: 0,
    price: 0,
    compatibility: [
      "Fiat Hitachi EX355",
      "Fiat Hitachi EX355-3",
      "Fiat Hitachi FH330",
      "Fiat Hitachi FH330-3",
      "New Holland EX355",
      "New Holland EX355-3",
      "New Holland FH330",
      "New Holland FH330-3",
      "Hitachi EX300-3",
      "Hitachi EX300-5",
      "Hitachi ZX330",
      "Hitachi ZX330-3",
      "Hitachi ZX350",
      "Hitachi ZX350-3",
      "Hitachi ZX360",
      "Hitachi ZX360-3G",
      "John Deere 330CLC",
      "John Deere 350DLC",
    ],
    notes:
      "Manufacturer: Handok Hydraulic (South Korea) · Material: high-density hardened carbon steel · Surface: precision ground & polished to OEM micro-tolerances · Pump displacement 145cc · OEM xref: HPV145-CENTER-PIN, 3081023, 4243645, 71402450, HD-HPV145-CP · Fitment: Fiat Hitachi/New Holland main pump group; Hitachi rotary group central piston; John Deere main hydraulic cylinder barrel guide pin",
  },
];
