/** Valve Plate subcategory seed — Hydraulic Parts. */
import type { Part } from "@/lib/mock-data";

type Fit = { brand: string; models: string[] };

function flatCompat(groups: Fit[]): string[] {
  const out: string[] = [];
  for (const g of groups) {
    for (const m of g.models) out.push(`${g.brand} ${m}`);
  }
  return out;
}

function vp(opts: {
  id: string;
  partNumber: string;
  partNumbers: string[];
  name: string;
  quantity: number;
  manufacturer: string;
  /** Physical location number (Stand 10 / 23 / Floor 23 / Stand 30 / Stand 59). */
  boxNumber: 10 | 23 | 30 | 59;
  location: "Stand 10" | "Stand 23" | "Floor 23" | "Stand 30" | "Stand 59";
  fitment: Fit[];
  reorderAt?: number;
  componentType?: string;
}): Part {
  return {
    id: opts.id,
    partNumber: opts.partNumber,
    partNumbers: opts.partNumbers,
    name: opts.name,
    description: `${opts.manufacturer} · ${opts.name}`,
    category: "Hydraulic Parts",
    subcategory: "Valve Plate",
    boxNumber: opts.boxNumber,
    quantity: opts.quantity,
    reorderAt: opts.reorderAt ?? Math.max(1, Math.min(2, Math.floor(opts.quantity / 2) || 1)),
    cost: 0,
    price: 0,
    compatibility: flatCompat(opts.fitment),
    notes: [
      `Subcategory: Valve Plate`,
      opts.location,
      `Manufacturer: ${opts.manufacturer}`,
      opts.componentType ? `Type: ${opts.componentType}` : null,
      `OEM xref: ${opts.partNumbers.join(", ")}`,
    ]
      .filter(Boolean)
      .join(" · "),
  };
}

const handok = "Handok Hydraulic (South Korea)";
const engrenax = "Engrenax (Canada)";
const aftermarket = "Aftermarket Premium Grade";

/** Stand 10 / 23 / Floor 23 + Stand 30 / 59 Valve Plates */
export const valvePlateParts: Part[] = [
  // —— Stand 10 ——
  vp({
    id: "hydraulic-vp-5I-8628-s10",
    partNumber: "5I-8628",
    partNumbers: ["5I-8628", "5I8628", "M2X120"],
    name: "VALVE PLATE — M2X120",
    quantity: 12,
    manufacturer: engrenax,
    boxNumber: 10,
    location: "Stand 10",
    componentType: "Valve Plate",
    fitment: [
      {
        brand: "Caterpillar",
        models: ["315B L", "317B L", "318B", "320B", "320B L", "320C", "320D"],
      },
      { brand: "Kawasaki", models: ["M2X120"] },
      { brand: "Uchida", models: ["M2X120"] },
    ],
  }),
  vp({
    id: "hydraulic-vp-pv24-l-s10",
    partNumber: "PV24-VP-L",
    partNumbers: ["PV24-VP-L", "PV24", "SPV6-024", "Sundstrand PV24"],
    name: "Valve Plate (Left) — PV24 / SPV6-024",
    quantity: 2,
    manufacturer: aftermarket,
    boxNumber: 10,
    location: "Stand 10",
    componentType: "Valve Plate · Left (L)",
    fitment: [
      { brand: "Sauer-Danfoss", models: ["PV24", "SPV6-024"] },
      { brand: "Sundstrand", models: ["PV24", "SPV6-024"] },
    ],
  }),
  vp({
    id: "hydraulic-vp-960621-3-s10",
    partNumber: "960621-3",
    partNumbers: [
      "960621-3",
      "9606213",
      "18V107SR1R",
      "A8V107SR1R",
      "A8V107",
    ],
    name: "VALVE PLATE RIGHT — 18V107SR1R / A8V107",
    quantity: 2,
    manufacturer: handok,
    boxNumber: 10,
    location: "Stand 10",
    componentType: "Valve Plate · Right (R)",
    fitment: [
      { brand: "Rexroth", models: ["A8V107SR1R", "A8V107", "18V107SR1R"] },
      { brand: "Uchida", models: ["A8V107SR1R", "A8V107"] },
    ],
  }),
  vp({
    id: "hydraulic-vp-609-33158001-s10",
    partNumber: "609-33158001",
    partNumbers: [
      "609-33158001",
      "60933158001",
      "A8V107SR1R",
      "A8V107",
    ],
    name: "VALVE PLATE LEFT — A8V107SR1R",
    quantity: 1,
    manufacturer: handok,
    boxNumber: 10,
    location: "Stand 10",
    componentType: "Valve Plate · Left (L)",
    fitment: [
      { brand: "Rexroth", models: ["A8V107SR1R", "A8V107"] },
      { brand: "Uchida", models: ["A8V107SR1R", "A8V107"] },
    ],
  }),

  // —— Stand 30 (Handok) ——
  vp({
    id: "hydraulic-vp-kmf41-hd",
    partNumber: "KMF41-VP-HD",
    partNumbers: ["KMF41-VP-HD", "706-73-11220", "7067311220", "HD-KMF41-VP"],
    name: "Handok KMF41 Valve Plate (PC60-7)",
    quantity: 2,
    manufacturer: handok,
    boxNumber: 30,
    location: "Stand 30",
    fitment: [{ brand: "Komatsu", models: ["PC60-7", "PC70-7", "PC75UU-2", "PC78US-5", "PC78US-6"] }],
  }),
  vp({
    id: "hydraulic-vp-kmf90-old-hd",
    partNumber: "KMF90-VP-OLD-HD",
    partNumbers: ["KMF90-VP-OLD-HD", "HD-KMF90-VP-1PIN"],
    name: "Handok KMF90 Valve Plate (Old Type - 1 Pin - PC200-5)",
    quantity: 1,
    manufacturer: handok,
    boxNumber: 30,
    location: "Stand 30",
    fitment: [{ brand: "Komatsu", models: ["PC200-5", "PC200LC-5", "PC210-5", "PC220-5"] }],
  }),
  vp({
    id: "hydraulic-vp-kmf125-hd",
    partNumber: "KMF125-VP-HD",
    partNumbers: ["KMF125-VP-HD", "706-75-11220", "7067511220", "HD-KMF125-VP"],
    name: "Handok KMF125 Valve Plate",
    quantity: 2,
    manufacturer: handok,
    boxNumber: 30,
    location: "Stand 30",
    fitment: [{ brand: "Komatsu", models: ["PC300-5", "PC300-6", "PC350-6"] }],
  }),
  vp({
    id: "hydraulic-vp-kmf90-new-hd",
    partNumber: "KMF90-VP-NEW-HD",
    partNumbers: ["KMF90-VP-NEW-HD", "HD-KMF90-VP-NEW"],
    name: "Handok KMF90 Valve Plate (New Type - PC200-5)",
    quantity: 1,
    manufacturer: handok,
    boxNumber: 30,
    location: "Stand 30",
    fitment: [{ brand: "Komatsu", models: ["PC200-5", "PC200LC-5", "PC220-5"] }],
  }),
  vp({
    id: "hydraulic-vp-kmf90-pc200-3-2pin-hd",
    partNumber: "KMF90-VP-PC200-3-2PIN-HD",
    partNumbers: ["KMF90-VP-PC200-3-2PIN-HD", "HD-KMF90-VP-2PIN"],
    name: "Handok KMF90 Valve Plate (PC200-3 - 2 Pin)",
    quantity: 1,
    manufacturer: handok,
    boxNumber: 30,
    location: "Stand 30",
    fitment: [{ brand: "Komatsu", models: ["PC200-3", "PC200LC-3", "PC210-3", "PC220-3"] }],
  }),
  vp({
    id: "hydraulic-vp-kmf90-pc200-3-5-hd",
    partNumber: "KMF90-VP-PC200-3-5-HD",
    partNumbers: ["KMF90-VP-PC200-3-5-HD", "706-74-11220", "7067411220", "HD-KMF90-VP-3-5"],
    name: "Handok KMF90 Valve Plate (PC200-3/5 Universal)",
    quantity: 2,
    manufacturer: handok,
    boxNumber: 30,
    location: "Stand 30",
    fitment: [{ brand: "Komatsu", models: ["PC200-3", "PC200-5", "PC220-3", "PC220-5"] }],
  }),
  vp({
    id: "hydraulic-vp-hpv75-new-hd",
    partNumber: "HPV75-VP-NEW-HD",
    partNumbers: ["HPV75-VP-NEW-HD", "708-2G-13230", "7082G13230", "HD-HPV75-VP-NEW"],
    name: "Handok HPV75 Valve Plate (New Type - PC60-7)",
    quantity: 2,
    manufacturer: handok,
    boxNumber: 30,
    location: "Stand 30",
    fitment: [{ brand: "Komatsu", models: ["PC60-7", "PC70-7", "PC75UU-2", "PC78US-5", "PC78US-6"] }],
  }),
  vp({
    id: "hydraulic-vp-m2x150-170-hd",
    partNumber: "M2X150-170-VP-HD",
    partNumbers: ["M2X150-170-VP-HD", "M2X150-VP", "M2X170-VP", "HD-M2X150-170-VP"],
    name: "Handok M2X150/170 Valve Plate",
    quantity: 2,
    manufacturer: handok,
    boxNumber: 30,
    location: "Stand 30",
    fitment: [
      { brand: "Kawasaki", models: ["M2X150", "M2X150B", "M2X170", "M2X170B"] },
    ],
  }),
  vp({
    id: "hydraulic-vp-m2x120-hd",
    partNumber: "M2X120-VP-HD",
    partNumbers: ["M2X120-VP-HD", "M2X120-VP", "HD-M2X120-VP"],
    name: "Handok M2X120 Valve Plate",
    quantity: 1,
    manufacturer: handok,
    boxNumber: 30,
    location: "Stand 30",
    fitment: [{ brand: "Kawasaki", models: ["M2X120", "M2X120B"] }],
  }),
  vp({
    id: "hydraulic-vp-m2x63-hd",
    partNumber: "M2X63-VP-HD",
    partNumbers: ["M2X63-VP-HD", "M2X63-VP", "HD-M2X63-VP"],
    name: "Handok M2X63 Valve Plate",
    quantity: 1,
    manufacturer: handok,
    boxNumber: 30,
    location: "Stand 30",
    fitment: [{ brand: "Kawasaki", models: ["M2X63", "M2X63B"] }],
  }),
  vp({
    id: "hydraulic-vp-ap2d12-hd",
    partNumber: "AP2D12-VP-HD",
    partNumbers: ["AP2D12-VP-HD", "AP2D12-VP", "HD-AP2D12-VP"],
    name: "Handok AP2D12 Valve Plate",
    quantity: 1,
    manufacturer: handok,
    boxNumber: 30,
    location: "Stand 30",
    fitment: [
      { brand: "Uchida", models: ["AP2D12", "AP2D12LV", "AP2D12FL3"] },
      { brand: "Rexroth", models: ["AP2D12", "AP2D12LV", "AP2D12FL3"] },
    ],
  }),
  vp({
    id: "hydraulic-vp-gm35va-hd",
    partNumber: "GM35VA-VP-HD",
    partNumbers: ["GM35VA-VP-HD", "GM35VA-VP", "HD-GM35VA-VP"],
    name: "Handok GM35VA Valve Plate",
    quantity: 1,
    manufacturer: handok,
    boxNumber: 30,
    location: "Stand 30",
    fitment: [
      { brand: "Teijin Seiki", models: ["GM35VA"] },
      { brand: "Nabtesco", models: ["GM35VA"] },
    ],
  }),
  vp({
    id: "hydraulic-vp-hpv75-old-hd",
    partNumber: "HPV75-VP-OLD-HD",
    partNumbers: ["HPV75-VP-OLD-HD", "708-2G-13210", "7082G13210", "HD-HPV75-VP-OLD"],
    name: "Handok HPV75 Valve Plate (Old Type - PC60-7)",
    quantity: 2,
    manufacturer: handok,
    boxNumber: 30,
    location: "Stand 30",
    fitment: [{ brand: "Komatsu", models: ["PC60-7", "PC60-7E", "PC60-7-B"] }],
  }),

  // —— Stand / Floor 23 ——
  vp({
    id: "hydraulic-vp-a8vo160-r-hd",
    partNumber: "A8VO160-VP-R-HD",
    partNumbers: ["A8VO160-VP-R-HD", "HD-A8VO160-VP-R"],
    name: "Handok A8VO160 Valve Plate (Right)",
    quantity: 1,
    manufacturer: handok,
    boxNumber: 23,
    location: "Stand 23",
    fitment: [{ brand: "Rexroth", models: ["A8VO160", "A8VO160LA1HN1"] }],
  }),
  vp({
    id: "hydraulic-vp-a8vo160-l-hd",
    partNumber: "A8VO160-VP-L-HD",
    partNumbers: ["A8VO160-VP-L-HD", "HD-A8VO160-VP-L"],
    name: "Handok A8VO160 Valve Plate (Left)",
    quantity: 3,
    manufacturer: handok,
    boxNumber: 23,
    location: "Stand 23",
    fitment: [{ brand: "Rexroth", models: ["A8VO160", "A8VO160LA1HN1"] }],
  }),
  vp({
    id: "hydraulic-vp-a8vo107-l-eg",
    partNumber: "A8VO107-VP-L-EG",
    partNumbers: ["A8VO107-VP-L-EG", "EG-A8VO107-VP-L"],
    name: "Engrenax A8VO107 Valve Plate (Left)",
    quantity: 3,
    manufacturer: engrenax,
    boxNumber: 23,
    location: "Stand 23",
    fitment: [{ brand: "Rexroth", models: ["A8VO107", "A8VO107LA1HN1"] }],
  }),
  vp({
    id: "hydraulic-vp-a8vo160-r-eg",
    partNumber: "A8VO160-VP-R-EG",
    partNumbers: ["A8VO160-VP-R-EG", "EG-A8VO160-VP-R"],
    name: "Engrenax A8VO160 Valve Plate (Right)",
    quantity: 2,
    manufacturer: engrenax,
    boxNumber: 23,
    location: "Stand 23",
    fitment: [{ brand: "Rexroth", models: ["A8VO160", "A8VO160LA1HN1"] }],
  }),
  vp({
    id: "hydraulic-vp-a8vo107-r-eg",
    partNumber: "A8VO107-VP-R-EG",
    partNumbers: ["A8VO107-VP-R-EG", "EG-A8VO107-VP-R"],
    name: "Engrenax A8VO107 Valve Plate (Right)",
    quantity: 4,
    manufacturer: engrenax,
    boxNumber: 23,
    location: "Stand 23",
    fitment: [{ brand: "Rexroth", models: ["A8VO107", "A8VO107LA1HN1"] }],
  }),
  vp({
    id: "hydraulic-vp-a8vo200-r-eg",
    partNumber: "A8VO200-VP-R-EG",
    partNumbers: ["A8VO200-VP-R-EG", "EG-A8VO200-VP-R"],
    name: "Engrenax A8VO200 Valve Plate (Right)",
    quantity: 1,
    manufacturer: engrenax,
    boxNumber: 23,
    location: "Stand 23",
    fitment: [{ brand: "Rexroth", models: ["A8VO200"] }],
  }),
  vp({
    id: "hydraulic-vp-m2x150-170-eg",
    partNumber: "M2X150-170-VP-EG",
    partNumbers: ["M2X150-170-VP-EG", "EG-M2X150-170-VP"],
    name: "Engrenax M2X150/170 Valve Plate",
    quantity: 2,
    manufacturer: engrenax,
    boxNumber: 23,
    location: "Stand 23",
    fitment: [{ brand: "Kawasaki", models: ["M2X150", "M2X170"] }],
  }),
  vp({
    id: "hydraulic-vp-a7vo250-l-hd",
    partNumber: "A7VO250-VP-L-HD",
    partNumbers: ["A7VO250-VP-L-HD", "HD-A7VO250-VP-L"],
    name: "Handok A7VO250 L/EL Valve Plate (Left)",
    quantity: 3,
    manufacturer: handok,
    boxNumber: 23,
    location: "Stand 23",
    fitment: [{ brand: "Rexroth", models: ["A7VO250", "A7VO250L", "A7VO250EL"] }],
  }),
  vp({
    id: "hydraulic-vp-a8vo107-l-hd",
    partNumber: "A8VO107-VP-L-HD",
    partNumbers: ["A8VO107-VP-L-HD", "HD-A8VO107-VP-L"],
    name: "Handok A8VO107 Valve Plate (Left)",
    quantity: 2,
    manufacturer: handok,
    boxNumber: 23,
    location: "Stand 23",
    fitment: [{ brand: "Rexroth", models: ["A8VO107"] }],
  }),
  vp({
    id: "hydraulic-vp-a8vo107-r-hd",
    partNumber: "A8VO107-VP-R-HD",
    partNumbers: ["A8VO107-VP-R-HD", "HD-A8VO107-VP-R"],
    name: "Handok A8VO107 Valve Plate (Right)",
    quantity: 2,
    manufacturer: handok,
    boxNumber: 23,
    location: "Stand 23",
    fitment: [{ brand: "Rexroth", models: ["A8VO107"] }],
  }),
  vp({
    id: "hydraulic-vp-a8v86-l-esbr-hd",
    partNumber: "A8V86-VP-L-ESBR-HD",
    partNumbers: ["A8V86-VP-L-ESBR-HD", "HD-A8V86-VP-L"],
    name: "Handok A8V86 ESBR Valve Plate (Left)",
    quantity: 2,
    manufacturer: handok,
    boxNumber: 23,
    location: "Stand 23",
    fitment: [{ brand: "Rexroth", models: ["A8V86", "A8V86ESBR"] }],
  }),
  vp({
    id: "hydraulic-vp-a8v86-r-esbr-hd",
    partNumber: "A8V86-VP-R-ESBR-HD",
    partNumbers: ["A8V86-VP-R-ESBR-HD", "HD-A8V86-VP-R"],
    name: "Handok A8V86 ESBR Valve Plate (Right)",
    quantity: 2,
    manufacturer: handok,
    boxNumber: 23,
    location: "Stand 23",
    fitment: [{ brand: "Rexroth", models: ["A8V86", "A8V86ESBR"] }],
  }),
  vp({
    id: "hydraulic-vp-a8v59-l-esbr-hd",
    partNumber: "A8V59-VP-L-ESBR-HD",
    partNumbers: ["A8V59-VP-L-ESBR-HD", "HD-A8V59-VP-L"],
    name: "Handok A8V59 ESBR Valve Plate (Left)",
    quantity: 1,
    manufacturer: handok,
    boxNumber: 23,
    location: "Floor 23",
    fitment: [{ brand: "Rexroth", models: ["A8V59", "A8V59ESBR"] }],
  }),
  vp({
    id: "hydraulic-vp-a8v59-r-esbr-hd",
    partNumber: "A8V59-VP-R-ESBR-HD",
    partNumbers: ["A8V59-VP-R-ESBR-HD", "HD-A8V59-VP-R"],
    name: "Handok A8V59 ESBR Valve Plate (Right)",
    quantity: 1,
    manufacturer: handok,
    boxNumber: 23,
    location: "Floor 23",
    fitment: [{ brand: "Rexroth", models: ["A8V59", "A8V59ESBR"] }],
  }),
  vp({
    id: "hydraulic-vp-a8v107sr1r-l-hd",
    partNumber: "A8V107SR1R-VP-L-HD",
    partNumbers: ["A8V107SR1R-VP-L-HD", "HD-A8V107SR1R-VP-L"],
    name: "Handok A8V107SR1R Valve Plate (Left)",
    quantity: 1,
    manufacturer: handok,
    boxNumber: 23,
    location: "Floor 23",
    fitment: [{ brand: "Rexroth", models: ["A8V107SR1R"] }],
  }),
  vp({
    id: "hydraulic-vp-hmgf36-hd",
    partNumber: "HMGF36-VP-HD",
    partNumbers: ["HMGF36-VP-HD", "HD-HMGF36-VP"],
    name: "Handok HMGF36 Valve Plate",
    quantity: 4,
    manufacturer: handok,
    boxNumber: 23,
    location: "Floor 23",
    fitment: [{ brand: "Hydraulic Motors", models: ["HMGF36 Series"] }],
  }),
  vp({
    id: "hydraulic-vp-a8vo200-l-hd",
    partNumber: "A8VO200-VP-L-HD",
    partNumbers: ["A8VO200-VP-L-HD", "HD-A8VO200-VP-L"],
    name: "Handok A8VO200 Valve Plate (Left)",
    quantity: 1,
    manufacturer: handok,
    boxNumber: 23,
    location: "Floor 23",
    fitment: [{ brand: "Rexroth", models: ["A8VO200"] }],
  }),
  vp({
    id: "hydraulic-vp-a8vo200-r-hd",
    partNumber: "A8VO200-VP-R-HD",
    partNumbers: ["A8VO200-VP-R-HD", "HD-A8VO200-VP-R"],
    name: "Handok A8VO200 Valve Plate (Right)",
    quantity: 1,
    manufacturer: handok,
    boxNumber: 23,
    location: "Floor 23",
    fitment: [{ brand: "Rexroth", models: ["A8VO200"] }],
  }),

  // —— Aftermarket Premium Grade (Stand 23) ——
  vp({
    id: "hydraulic-vp-59828",
    partNumber: "59828",
    partNumbers: ["59828", "HD-59828"],
    name: "Valve Plate (HMGF35 / HMV116)",
    quantity: 1,
    manufacturer: handok,
    boxNumber: 23,
    location: "Stand 23",
    fitment: [
      { brand: "Hitachi", models: ["HMGF35", "HMV116"] },
    ],
  }),
  vp({
    id: "hydraulic-vp-365315",
    partNumber: "365315",
    partNumbers: ["365315", "HD-365315"],
    name: "Valve Plate (M2X150)",
    quantity: 1,
    manufacturer: handok,
    boxNumber: 23,
    location: "Stand 23",
    fitment: [{ brand: "Kawasaki", models: ["M2X150"] }],
  }),
  vp({
    id: "hydraulic-vp-0350307",
    partNumber: "0350307",
    partNumbers: ["0350307", "HD-0350307"],
    name: "Valve Plate L (A7VO250L/EL)",
    quantity: 1,
    manufacturer: handok,
    boxNumber: 23,
    location: "Stand 23",
    componentType: "Valve Plate · Left (L)",
    fitment: [
      { brand: "Rexroth", models: ["A7VO250L", "A7VO250EL"] },
    ],
  }),
  vp({
    id: "hydraulic-vp-yc35-6-af",
    partNumber: "YC35-6-VP-AF",
    partNumbers: ["YC35-6-VP-AF", "YC35-6-VP", "AF-YC35-6-VP"],
    name: "Aftermarket YC35-6 Valve Plate",
    quantity: 1,
    manufacturer: aftermarket,
    boxNumber: 23,
    location: "Stand 23",
    fitment: [{ brand: "Yuchai", models: ["YC35-6", "YC35", "YC35SR"] }],
  }),
  vp({
    id: "hydraulic-vp-ap2d36-r-af",
    partNumber: "AP2D36-VP-R-AF",
    partNumbers: ["AP2D36-VP-R-AF", "AP2D36-VP-R", "AF-AP2D36-VP-R"],
    name: "Aftermarket AP2D36 Valve Plate (Right)",
    quantity: 1,
    manufacturer: aftermarket,
    boxNumber: 23,
    location: "Stand 23",
    fitment: [
      { brand: "Uchida", models: ["AP2D36", "AP2D36LV"] },
      { brand: "Rexroth", models: ["AP2D36", "AP2D36LV"] },
      { brand: "Komatsu", models: ["PC50MR-2", "PC55MR-2"] },
      { brand: "Takeuchi", models: ["TB145", "TB153"] },
    ],
  }),
  vp({
    id: "hydraulic-vp-a10vo71-l-af",
    partNumber: "A10VO71-VP-L-AF",
    partNumbers: ["A10VO71-VP-L-AF", "A10VO71-VP-L", "AF-A10VO71-VP-L", "A10VO71FLR"],
    name: "Aftermarket A10VO71 Valve Plate (Left)",
    quantity: 1,
    manufacturer: aftermarket,
    boxNumber: 23,
    location: "Stand 23",
    fitment: [{ brand: "Rexroth", models: ["A10VO71", "A10VO71DFR", "A10VO71DR"] }],
  }),
  // —— Stand 59 ——
  vp({
    id: "hydraulic-vp-28318",
    partNumber: "28318",
    partNumbers: ["28318", "HD-28318"],
    name: "Link/Lever of Valve Plate (HPV116)",
    quantity: 10,
    manufacturer: handok,
    boxNumber: 59,
    location: "Stand 59",
    componentType: "Valve Plate Link",
    fitment: [{ brand: "Komatsu", models: ["HPV116"] }],
  }),
];
