/** Kafu 2025 product catalog import (Part # = Kafu code, categories per section). */
export const kafuParts = [
  {
    id: "kafu-a01-1",
    partNumber: "A01-1",
    name: "Revolution Sensor — PC200-7",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Komatsu PC200-7"],
    notes: "OEM: 7861-93-2330 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-10",
    partNumber: "A01-10",
    name: "Revolution Sensor — SK200-6/6E",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Kobelco SK200-6"],
    notes: "OEM: ME844577 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-10a",
    partNumber: "A01-10A",
    name: "Revolution Sensor — SANY",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["SANY"],
    notes: "OEM: MC867505 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-14",
    partNumber: "A01-14",
    name: "Revolution Sensor — EX200 / EX120",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Hitachi EX200", "Hitachi EX120"],
    notes: "OEM: 4265372 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-15",
    partNumber: "A01-15",
    name: "Revolution Sensor — ZAX450",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Hitachi ZAX450"],
    notes: "OEM: 1-81510713-1 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-1a",
    partNumber: "A01-1A",
    name: "Revolution Sensor — Hitachi",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Hitachi"],
    notes: "OEM: 2055358 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-1b",
    partNumber: "A01-1B",
    name: "Revolution Sensor — WA500-1",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Komatsu WA500-1"],
    notes: "OEM: 7819-11-2315 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-2",
    partNumber: "A01-2",
    name: "Revolution Sensor — PC200-5/6 PC220-6",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Komatsu PC200-5", "Komatsu PC200-6", "Komatsu PC220-6"],
    notes: "OEM: 7861-92-2330 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-21",
    partNumber: "A01-21",
    name: "Revolution Sensor — Liugong",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Liugong"],
    notes: "OEM: 30T815, 4884223 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-21c",
    partNumber: "A01-21C",
    name: "Revolution Sensor — PC1250-7 / ZAX1200",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Komatsu PC1250-7", "Hitachi ZAX1200"],
    notes: "OEM: 4327239, 3408472 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-278",
    partNumber: "A01-278",
    name: "Revolution Sensor — A01-278",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a01-27k",
    partNumber: "A01-27K",
    name: "Revolution Sensor — A01-27K",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a01-2b",
    partNumber: "A01-2B",
    name: "Revolution Sensor — PC360-8",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Komatsu PC360-8"],
    notes: "OEM: 31121 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-4",
    partNumber: "A01-4",
    name: "Revolution Sensor — A01-4",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a01-43a",
    partNumber: "A01-43A",
    name: "Revolution Sensor — A01-43A",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a01-46",
    partNumber: "A01-46",
    name: "Revolution Sensor — A01-46",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a01-47",
    partNumber: "A01-47",
    name: "Revolution Sensor — A01-47",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a01-49",
    partNumber: "A01-49",
    name: "Revolution Sensor — A01-49",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a01-5",
    partNumber: "A01-5",
    name: "Revolution Sensor — E329",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Caterpillar E329"],
    notes: "OEM: 193-2550, 318-1178, 318-1181 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-50",
    partNumber: "A01-50",
    name: "Revolution Sensor — A01-50",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a01-53",
    partNumber: "A01-53",
    name: "Revolution Sensor — A01-53",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a01-54",
    partNumber: "A01-54",
    name: "Revolution Sensor — A01-54",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a01-55",
    partNumber: "A01-55",
    name: "Revolution Sensor — A01-55",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a01-9",
    partNumber: "A01-9",
    name: "Revolution Sensor — SK200-3/5",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Kobelco SK200-3", "Kobelco SK200-5"],
    notes: "OEM: ME845235 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-10",
    partNumber: "A02-10",
    name: "Camshaft Sensor — A02-10",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-10a",
    partNumber: "A02-10A",
    name: "Camshaft Sensor — A02-10A",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-12",
    partNumber: "A02-12",
    name: "Camshaft Sensor — A02-12",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-12a",
    partNumber: "A02-12A",
    name: "Camshaft Sensor — A02-12A",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-13",
    partNumber: "A02-13",
    name: "Camshaft Sensor — A02-13",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-15",
    partNumber: "A02-15",
    name: "Camshaft Sensor — A02-15",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-17",
    partNumber: "A02-17",
    name: "Camshaft Sensor — A02-17",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-18",
    partNumber: "A02-18",
    name: "Camshaft Sensor — A02-18",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-19",
    partNumber: "A02-19",
    name: "Camshaft Sensor — A02-19",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-1a",
    partNumber: "A02-1A",
    name: "Camshaft Sensor — A02-1A",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-1b",
    partNumber: "A02-1B",
    name: "Camshaft Sensor — A02-1B",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-20",
    partNumber: "A02-20",
    name: "Camshaft Sensor — A02-20",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-21",
    partNumber: "A02-21",
    name: "Camshaft Sensor — A02-21",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-22",
    partNumber: "A02-22",
    name: "Camshaft Sensor — A02-22",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-23",
    partNumber: "A02-23",
    name: "Camshaft Sensor — A02-23",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-23a",
    partNumber: "A02-23A",
    name: "Camshaft Sensor — A02-23A",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-24",
    partNumber: "A02-24",
    name: "Camshaft Sensor — A02-24",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-25",
    partNumber: "A02-25",
    name: "Camshaft Sensor — A02-25",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-26",
    partNumber: "A02-26",
    name: "Camshaft Sensor — A02-26",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-26a",
    partNumber: "A02-26A",
    name: "Camshaft Sensor — A02-26A",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-27",
    partNumber: "A02-27",
    name: "Camshaft Sensor — A02-27",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-27a",
    partNumber: "A02-27A",
    name: "Camshaft Sensor — A02-27A",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-28",
    partNumber: "A02-28",
    name: "Camshaft Sensor — A02-28",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-288",
    partNumber: "A02-288",
    name: "Camshaft Sensor — A02-288",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-28a",
    partNumber: "A02-28A",
    name: "Camshaft Sensor — A02-28A",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-29",
    partNumber: "A02-29",
    name: "Camshaft Sensor — A02-29",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-298",
    partNumber: "A02-298",
    name: "Camshaft Sensor — A02-298",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-30",
    partNumber: "A02-30",
    name: "Camshaft Sensor — A02-30",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-31",
    partNumber: "A02-31",
    name: "Camshaft Sensor — A02-31",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-32",
    partNumber: "A02-32",
    name: "Camshaft Sensor — A02-32",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-32a",
    partNumber: "A02-32A",
    name: "Camshaft Sensor — A02-32A",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-33",
    partNumber: "A02-33",
    name: "Camshaft Sensor — A02-33",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-34",
    partNumber: "A02-34",
    name: "Camshaft Sensor — A02-34",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-35",
    partNumber: "A02-35",
    name: "Camshaft Sensor — A02-35",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-36",
    partNumber: "A02-36",
    name: "Camshaft Sensor — A02-36",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-37",
    partNumber: "A02-37",
    name: "Camshaft Sensor — A02-37",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-39",
    partNumber: "A02-39",
    name: "Camshaft Sensor — A02-39",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-40",
    partNumber: "A02-40",
    name: "Camshaft Sensor — A02-40",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-41",
    partNumber: "A02-41",
    name: "Camshaft Sensor — A02-41",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-42",
    partNumber: "A02-42",
    name: "Camshaft Sensor — A02-42",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-44",
    partNumber: "A02-44",
    name: "Camshaft Sensor — A02-44",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-44a",
    partNumber: "A02-44A",
    name: "Camshaft Sensor — A02-44A",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-45",
    partNumber: "A02-45",
    name: "Camshaft Sensor — A02-45",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-46",
    partNumber: "A02-46",
    name: "Camshaft Sensor — A02-46",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-47",
    partNumber: "A02-47",
    name: "Camshaft Sensor — A02-47",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-4a",
    partNumber: "A02-4A",
    name: "Camshaft Sensor — A02-4A",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-5a",
    partNumber: "A02-5A",
    name: "Camshaft Sensor — A02-5A",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-10",
    partNumber: "A03-10",
    name: "Air Pressure Sensor — A03-10",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-11",
    partNumber: "A03-11",
    name: "Air Pressure Sensor — A03-11",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-118",
    partNumber: "A03-118",
    name: "Air Pressure Sensor — A03-118",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-11a",
    partNumber: "A03-11A",
    name: "Air Pressure Sensor — A03-11A",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-120",
    partNumber: "A03-120",
    name: "Air Pressure Sensor — A03-120",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-128",
    partNumber: "A03-128",
    name: "Air Pressure Sensor — A03-128",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-12a",
    partNumber: "A03-12A",
    name: "Air Pressure Sensor — A03-12A",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-13",
    partNumber: "A03-13",
    name: "Air Pressure Sensor — A03-13",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-13a",
    partNumber: "A03-13A",
    name: "Air Pressure Sensor — A03-13A",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-14",
    partNumber: "A03-14",
    name: "Air Pressure Sensor — A03-14",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-14a",
    partNumber: "A03-14A",
    name: "Air Pressure Sensor — A03-14A",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-15",
    partNumber: "A03-15",
    name: "Air Pressure Sensor — A03-15",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-15a",
    partNumber: "A03-15A",
    name: "Air Pressure Sensor — A03-15A",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-16",
    partNumber: "A03-16",
    name: "Air Pressure Sensor — A03-16",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-17",
    partNumber: "A03-17",
    name: "Air Pressure Sensor — A03-17",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-18",
    partNumber: "A03-18",
    name: "Air Pressure Sensor — A03-18",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-18a",
    partNumber: "A03-18A",
    name: "Air Pressure Sensor — A03-18A",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-19",
    partNumber: "A03-19",
    name: "Air Pressure Sensor — A03-19",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-2",
    partNumber: "A03-2",
    name: "Air Pressure Sensor — A03-2",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-20",
    partNumber: "A03-20",
    name: "Air Pressure Sensor — A03-20",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-21",
    partNumber: "A03-21",
    name: "Air Pressure Sensor — A03-21",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-22",
    partNumber: "A03-22",
    name: "Air Pressure Sensor — A03-22",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-228",
    partNumber: "A03-228",
    name: "Air Pressure Sensor — A03-228",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-23",
    partNumber: "A03-23",
    name: "Air Pressure Sensor — A03-23",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-25a",
    partNumber: "A03-25A",
    name: "Air Pressure Sensor — A03-25A",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-26a",
    partNumber: "A03-26A",
    name: "Air Pressure Sensor — A03-26A",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-28",
    partNumber: "A03-28",
    name: "Air Pressure Sensor — A03-28",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-29",
    partNumber: "A03-29",
    name: "Air Pressure Sensor — A03-29",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-31",
    partNumber: "A03-31",
    name: "Air Pressure Sensor — A03-31",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-32",
    partNumber: "A03-32",
    name: "Air Pressure Sensor — A03-32",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-33",
    partNumber: "A03-33",
    name: "Air Pressure Sensor — A03-33",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-35",
    partNumber: "A03-35",
    name: "Air Pressure Sensor — A03-35",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-36",
    partNumber: "A03-36",
    name: "Air Pressure Sensor — A03-36",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-37",
    partNumber: "A03-37",
    name: "Air Pressure Sensor — A03-37",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-38",
    partNumber: "A03-38",
    name: "Air Pressure Sensor — A03-38",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-39",
    partNumber: "A03-39",
    name: "Air Pressure Sensor — A03-39",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-40",
    partNumber: "A03-40",
    name: "Air Pressure Sensor — A03-40",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-41",
    partNumber: "A03-41",
    name: "Air Pressure Sensor — A03-41",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-5",
    partNumber: "A03-5",
    name: "Air Pressure Sensor — A03-5",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-5a",
    partNumber: "A03-5A",
    name: "Air Pressure Sensor — A03-5A",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-6",
    partNumber: "A03-6",
    name: "Air Pressure Sensor — A03-6",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-68",
    partNumber: "A03-68",
    name: "Air Pressure Sensor — A03-68",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-6a",
    partNumber: "A03-6A",
    name: "Air Pressure Sensor — A03-6A",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-8",
    partNumber: "A03-8",
    name: "Air Pressure Sensor — A03-8",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-9",
    partNumber: "A03-9",
    name: "Air Pressure Sensor — A03-9",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-98",
    partNumber: "A03-98",
    name: "Air Pressure Sensor — A03-98",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-9a",
    partNumber: "A03-9A",
    name: "Air Pressure Sensor — A03-9A",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-10",
    partNumber: "A04-10",
    name: "Oil Pressure Switch — A04-10",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-13",
    partNumber: "A04-13",
    name: "Oil Pressure Switch — A04-13",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-18",
    partNumber: "A04-18",
    name: "Oil Pressure Switch — A04-18",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-188",
    partNumber: "A04-188",
    name: "Oil Pressure Switch — A04-188",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-18f",
    partNumber: "A04-18F",
    name: "Oil Pressure Switch — A04-18F",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-208",
    partNumber: "A04-208",
    name: "Oil Pressure Switch — A04-208",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-254",
    partNumber: "A04-254",
    name: "Oil Pressure Switch — A04-254",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-28",
    partNumber: "A04-28",
    name: "Oil Pressure Switch — A04-28",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-49",
    partNumber: "A04-49",
    name: "Oil Pressure Switch — A04-49",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-55b",
    partNumber: "A04-55B",
    name: "Oil Pressure Switch — A04-55B",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-56b",
    partNumber: "A04-56B",
    name: "Oil Pressure Switch — A04-56B",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-58a",
    partNumber: "A04-58A",
    name: "Oil Pressure Switch — A04-58A",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-59",
    partNumber: "A04-59",
    name: "Oil Pressure Switch — A04-59",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-6a",
    partNumber: "A04-6A",
    name: "Oil Pressure Switch — A04-6A",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-7",
    partNumber: "A04-7",
    name: "Oil Pressure Switch — A04-7",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-75",
    partNumber: "A04-75",
    name: "Oil Pressure Switch — A04-75",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-78",
    partNumber: "A04-78",
    name: "Oil Pressure Switch — A04-78",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-7a",
    partNumber: "A04-7A",
    name: "Oil Pressure Switch — A04-7A",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-98",
    partNumber: "A04-98",
    name: "Oil Pressure Switch — A04-98",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-9a",
    partNumber: "A04-9A",
    name: "Oil Pressure Switch — A04-9A",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a05-10",
    partNumber: "A05-10",
    name: "Water Temp Sensor — A05-10",
    category: "Water Temp Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a05-14",
    partNumber: "A05-14",
    name: "Water Temp Sensor — A05-14",
    category: "Water Temp Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a05-168",
    partNumber: "A05-168",
    name: "Water Temp Sensor — A05-168",
    category: "Water Temp Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a05-220",
    partNumber: "A05-220",
    name: "Water Temp Sensor — A05-220",
    category: "Water Temp Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a05-226",
    partNumber: "A05-226",
    name: "Water Temp Sensor — A05-226",
    category: "Water Temp Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a05-228",
    partNumber: "A05-228",
    name: "Water Temp Sensor — A05-228",
    category: "Water Temp Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a05-22e",
    partNumber: "A05-22E",
    name: "Water Temp Sensor — A05-22E",
    category: "Water Temp Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a05-22f",
    partNumber: "A05-22F",
    name: "Water Temp Sensor — A05-22F",
    category: "Water Temp Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-102",
    partNumber: "A06-102",
    name: "Pressure Switch — A06-102",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-104",
    partNumber: "A06-104",
    name: "Pressure Switch — A06-104",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-108",
    partNumber: "A06-108",
    name: "Pressure Switch — A06-108",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-110",
    partNumber: "A06-110",
    name: "Pressure Switch — A06-110",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-114",
    partNumber: "A06-114",
    name: "Pressure Switch — A06-114",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-117",
    partNumber: "A06-117",
    name: "Pressure Switch — A06-117",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-118",
    partNumber: "A06-118",
    name: "Pressure Switch — A06-118",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-129",
    partNumber: "A06-129",
    name: "Pressure Switch — A06-129",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-130",
    partNumber: "A06-130",
    name: "Pressure Switch — A06-130",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-132",
    partNumber: "A06-132",
    name: "Pressure Switch — A06-132",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-134",
    partNumber: "A06-134",
    name: "Pressure Switch — A06-134",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-137",
    partNumber: "A06-137",
    name: "Pressure Switch — A06-137",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-145",
    partNumber: "A06-145",
    name: "Pressure Switch — A06-145",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-20",
    partNumber: "A06-20",
    name: "Pressure Switch — A06-20",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-208",
    partNumber: "A06-208",
    name: "Pressure Switch — A06-208",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-21a",
    partNumber: "A06-21A",
    name: "Pressure Switch — A06-21A",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-228",
    partNumber: "A06-228",
    name: "Pressure Switch — A06-228",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-244",
    partNumber: "A06-244",
    name: "Pressure Switch — A06-244",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-24n",
    partNumber: "A06-24N",
    name: "Pressure Switch — A06-24N",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-44",
    partNumber: "A06-44",
    name: "Pressure Switch — A06-44",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-72a",
    partNumber: "A06-72A",
    name: "Pressure Switch — A06-72A",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-79",
    partNumber: "A06-79",
    name: "Pressure Switch — A06-79",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-79a",
    partNumber: "A06-79A",
    name: "Pressure Switch — A06-79A",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-84a",
    partNumber: "A06-84A",
    name: "Pressure Switch — A06-84A",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-85",
    partNumber: "A06-85",
    name: "Pressure Switch — A06-85",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-86d",
    partNumber: "A06-86D",
    name: "Pressure Switch — A06-86D",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-88",
    partNumber: "A06-88",
    name: "Pressure Switch — A06-88",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-88a",
    partNumber: "A06-88A",
    name: "Pressure Switch — A06-88A",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-98",
    partNumber: "A06-98",
    name: "Pressure Switch — A06-98",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a06-9a",
    partNumber: "A06-9A",
    name: "Pressure Switch — A06-9A",
    category: "Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a07-23",
    partNumber: "A07-23",
    name: "Common Rail Sensor — A07-23",
    category: "Common Rail Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a07-288",
    partNumber: "A07-288",
    name: "Common Rail Sensor — A07-288",
    category: "Common Rail Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a07-7a",
    partNumber: "A07-7A",
    name: "Common Rail Sensor — A07-7A",
    category: "Common Rail Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a08-1",
    partNumber: "A08-1",
    name: "High-pressure Oil Pump — A08-1",
    category: "High-pressure Oil Pump",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a08-10",
    partNumber: "A08-10",
    name: "High-pressure Oil Pump — A08-10",
    category: "High-pressure Oil Pump",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a08-12",
    partNumber: "A08-12",
    name: "High-pressure Oil Pump — A08-12",
    category: "High-pressure Oil Pump",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a08-13",
    partNumber: "A08-13",
    name: "High-pressure Oil Pump — A08-13",
    category: "High-pressure Oil Pump",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a08-14",
    partNumber: "A08-14",
    name: "High-pressure Oil Pump — A08-14",
    category: "High-pressure Oil Pump",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a08-6",
    partNumber: "A08-6",
    name: "High-pressure Oil Pump — A08-6",
    category: "High-pressure Oil Pump",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a09-1",
    partNumber: "A09-1",
    name: "Starter Relay — A09-1",
    category: "Starter Relay",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a09-15e",
    partNumber: "A09-15E",
    name: "Starter Relay — A09-15E",
    category: "Starter Relay",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a09-2a",
    partNumber: "A09-2A",
    name: "Starter Relay — A09-2A",
    category: "Starter Relay",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a09-34",
    partNumber: "A09-34",
    name: "Starter Relay — A09-34",
    category: "Starter Relay",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a09-344",
    partNumber: "A09-344",
    name: "Starter Relay — A09-344",
    category: "Starter Relay",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a09-3a",
    partNumber: "A09-3A",
    name: "Starter Relay — A09-3A",
    category: "Starter Relay",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a09-6",
    partNumber: "A09-6",
    name: "Starter Relay — A09-6",
    category: "Starter Relay",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a12-208",
    partNumber: "A12-208",
    name: "Accelerator Motor — A12-208",
    category: "Accelerator Motor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a12-248",
    partNumber: "A12-248",
    name: "Accelerator Motor — A12-248",
    category: "Accelerator Motor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a12-288",
    partNumber: "A12-288",
    name: "Accelerator Motor — A12-288",
    category: "Accelerator Motor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a12-320",
    partNumber: "A12-320",
    name: "Accelerator Motor — A12-320",
    category: "Accelerator Motor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a12-32a",
    partNumber: "A12-32A",
    name: "Accelerator Motor — A12-32A",
    category: "Accelerator Motor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a12-32b",
    partNumber: "A12-32B",
    name: "Accelerator Motor — A12-32B",
    category: "Accelerator Motor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a12-32d",
    partNumber: "A12-32D",
    name: "Accelerator Motor — A12-32D",
    category: "Accelerator Motor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a12-33",
    partNumber: "A12-33",
    name: "Accelerator Motor — A12-33",
    category: "Accelerator Motor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a13-1",
    partNumber: "A13-1",
    name: "Time Meter — A13-1",
    category: "Time Meter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a13-138",
    partNumber: "A13-138",
    name: "Time Meter — A13-138",
    category: "Time Meter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a13-13a",
    partNumber: "A13-13A",
    name: "Time Meter — A13-13A",
    category: "Time Meter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a13-2",
    partNumber: "A13-2",
    name: "Time Meter — A13-2",
    category: "Time Meter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a13-3",
    partNumber: "A13-3",
    name: "Time Meter — A13-3",
    category: "Time Meter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a13-40a",
    partNumber: "A13-40A",
    name: "Time Meter — A13-40A",
    category: "Time Meter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a13-6a",
    partNumber: "A13-6A",
    name: "Time Meter — A13-6A",
    category: "Time Meter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-13a",
    partNumber: "A14-13A",
    name: "Solenoid Valve — A14-13A",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-14a",
    partNumber: "A14-14A",
    name: "Solenoid Valve — A14-14A",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-168",
    partNumber: "A14-168",
    name: "Solenoid Valve — A14-168",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-16a",
    partNumber: "A14-16A",
    name: "Solenoid Valve — A14-16A",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-204",
    partNumber: "A14-204",
    name: "Solenoid Valve — A14-204",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-22",
    partNumber: "A14-22",
    name: "Solenoid Valve — A14-22",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-23",
    partNumber: "A14-23",
    name: "Solenoid Valve — A14-23",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-23a",
    partNumber: "A14-23A",
    name: "Solenoid Valve — A14-23A",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-244",
    partNumber: "A14-244",
    name: "Solenoid Valve — A14-244",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-254",
    partNumber: "A14-254",
    name: "Solenoid Valve — A14-254",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-268",
    partNumber: "A14-268",
    name: "Solenoid Valve — A14-268",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-27",
    partNumber: "A14-27",
    name: "Solenoid Valve — A14-27",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-270",
    partNumber: "A14-270",
    name: "Solenoid Valve — A14-270",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-278",
    partNumber: "A14-278",
    name: "Solenoid Valve — A14-278",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-27a",
    partNumber: "A14-27A",
    name: "Solenoid Valve — A14-27A",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-288",
    partNumber: "A14-288",
    name: "Solenoid Valve — A14-288",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-29",
    partNumber: "A14-29",
    name: "Solenoid Valve — A14-29",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-30",
    partNumber: "A14-30",
    name: "Solenoid Valve — A14-30",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-30a",
    partNumber: "A14-30A",
    name: "Solenoid Valve — A14-30A",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-31",
    partNumber: "A14-31",
    name: "Solenoid Valve — A14-31",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-328",
    partNumber: "A14-328",
    name: "Solenoid Valve — A14-328",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-33",
    partNumber: "A14-33",
    name: "Solenoid Valve — A14-33",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-330",
    partNumber: "A14-330",
    name: "Solenoid Valve — A14-330",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-338",
    partNumber: "A14-338",
    name: "Solenoid Valve — A14-338",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-33a",
    partNumber: "A14-33A",
    name: "Solenoid Valve — A14-33A",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-33e",
    partNumber: "A14-33E",
    name: "Solenoid Valve — A14-33E",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-34",
    partNumber: "A14-34",
    name: "Solenoid Valve — A14-34",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-368",
    partNumber: "A14-368",
    name: "Solenoid Valve — A14-368",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-378",
    partNumber: "A14-378",
    name: "Solenoid Valve — A14-378",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-37a",
    partNumber: "A14-37A",
    name: "Solenoid Valve — A14-37A",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-38",
    partNumber: "A14-38",
    name: "Solenoid Valve — A14-38",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-40",
    partNumber: "A14-40",
    name: "Solenoid Valve — A14-40",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-40a",
    partNumber: "A14-40A",
    name: "Solenoid Valve — A14-40A",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-41a",
    partNumber: "A14-41A",
    name: "Solenoid Valve — A14-41A",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-42",
    partNumber: "A14-42",
    name: "Solenoid Valve — A14-42",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-43",
    partNumber: "A14-43",
    name: "Solenoid Valve — A14-43",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-44",
    partNumber: "A14-44",
    name: "Solenoid Valve — A14-44",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-45",
    partNumber: "A14-45",
    name: "Solenoid Valve — A14-45",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-45a",
    partNumber: "A14-45A",
    name: "Solenoid Valve — A14-45A",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-45e",
    partNumber: "A14-45E",
    name: "Solenoid Valve — A14-45E",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-46a",
    partNumber: "A14-46A",
    name: "Solenoid Valve — A14-46A",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-47",
    partNumber: "A14-47",
    name: "Solenoid Valve — A14-47",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-48a",
    partNumber: "A14-48A",
    name: "Solenoid Valve — A14-48A",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-52",
    partNumber: "A14-52",
    name: "Solenoid Valve — A14-52",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-53",
    partNumber: "A14-53",
    name: "Solenoid Valve — A14-53",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-53a",
    partNumber: "A14-53A",
    name: "Solenoid Valve — A14-53A",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-53b",
    partNumber: "A14-53B",
    name: "Solenoid Valve — A14-53B",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-57",
    partNumber: "A14-57",
    name: "Solenoid Valve — A14-57",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a14-58",
    partNumber: "A14-58",
    name: "Solenoid Valve — A14-58",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a15-10a",
    partNumber: "A15-10A",
    name: "Ignition Switch — A15-10A",
    category: "Ignition Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a15-16a",
    partNumber: "A15-16A",
    name: "Ignition Switch — A15-16A",
    category: "Ignition Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a15-198",
    partNumber: "A15-198",
    name: "Ignition Switch — A15-198",
    category: "Ignition Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a15-228",
    partNumber: "A15-228",
    name: "Ignition Switch — A15-228",
    category: "Ignition Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a15-25",
    partNumber: "A15-25",
    name: "Ignition Switch — A15-25",
    category: "Ignition Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a15-268",
    partNumber: "A15-268",
    name: "Ignition Switch — A15-268",
    category: "Ignition Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a15-30",
    partNumber: "A15-30",
    name: "Ignition Switch — A15-30",
    category: "Ignition Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a17-130",
    partNumber: "A17-130",
    name: "Fan Clutch — A17-130",
    category: "Fan Clutch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a17-138",
    partNumber: "A17-138",
    name: "Fan Clutch — A17-138",
    category: "Fan Clutch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a17-13a",
    partNumber: "A17-13A",
    name: "Fan Clutch — A17-13A",
    category: "Fan Clutch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a17-13e",
    partNumber: "A17-13E",
    name: "Fan Clutch — A17-13E",
    category: "Fan Clutch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a17-13f",
    partNumber: "A17-13F",
    name: "Fan Clutch — A17-13F",
    category: "Fan Clutch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a17-20",
    partNumber: "A17-20",
    name: "Fan Clutch — A17-20",
    category: "Fan Clutch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a17-21",
    partNumber: "A17-21",
    name: "Fan Clutch — A17-21",
    category: "Fan Clutch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a17-22",
    partNumber: "A17-22",
    name: "Fan Clutch — A17-22",
    category: "Fan Clutch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a17-22a",
    partNumber: "A17-22A",
    name: "Fan Clutch — A17-22A",
    category: "Fan Clutch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a17-23",
    partNumber: "A17-23",
    name: "Fan Clutch — A17-23",
    category: "Fan Clutch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a17-230",
    partNumber: "A17-230",
    name: "Fan Clutch — A17-230",
    category: "Fan Clutch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a17-236",
    partNumber: "A17-236",
    name: "Fan Clutch — A17-236",
    category: "Fan Clutch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a17-238",
    partNumber: "A17-238",
    name: "Fan Clutch — A17-238",
    category: "Fan Clutch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a17-23f",
    partNumber: "A17-23F",
    name: "Fan Clutch — A17-23F",
    category: "Fan Clutch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a17-23h",
    partNumber: "A17-23H",
    name: "Fan Clutch — A17-23H",
    category: "Fan Clutch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a17-24",
    partNumber: "A17-24",
    name: "Fan Clutch — A17-24",
    category: "Fan Clutch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a17-25",
    partNumber: "A17-25",
    name: "Fan Clutch — A17-25",
    category: "Fan Clutch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a17-30",
    partNumber: "A17-30",
    name: "Fan Clutch — A17-30",
    category: "Fan Clutch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a17-34",
    partNumber: "A17-34",
    name: "Fan Clutch — A17-34",
    category: "Fan Clutch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a17-38",
    partNumber: "A17-38",
    name: "Fan Clutch — A17-38",
    category: "Fan Clutch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a17-42",
    partNumber: "A17-42",
    name: "Fan Clutch — A17-42",
    category: "Fan Clutch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a17-44",
    partNumber: "A17-44",
    name: "Fan Clutch — A17-44",
    category: "Fan Clutch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a18-2",
    partNumber: "A18-2",
    name: "Monitor — A18-2",
    category: "Monitor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a18-28",
    partNumber: "A18-28",
    name: "Monitor — A18-28",
    category: "Monitor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a18-2a",
    partNumber: "A18-2A",
    name: "Monitor — A18-2A",
    category: "Monitor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a18-2f",
    partNumber: "A18-2F",
    name: "Monitor — A18-2F",
    category: "Monitor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a18-3a",
    partNumber: "A18-3A",
    name: "Monitor — A18-3A",
    category: "Monitor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a20-14",
    partNumber: "A20-14",
    name: "Wiper Motor — A20-14",
    category: "Wiper Motor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a20-17a",
    partNumber: "A20-17A",
    name: "Wiper Motor — A20-17A",
    category: "Wiper Motor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a20-44",
    partNumber: "A20-44",
    name: "Wiper Motor — A20-44",
    category: "Wiper Motor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a21-16a",
    partNumber: "A21-16A",
    name: "Starting Motor — A21-16A",
    category: "Starting Motor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a21-198",
    partNumber: "A21-198",
    name: "Starting Motor — A21-198",
    category: "Starting Motor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a21-204",
    partNumber: "A21-204",
    name: "Starting Motor — A21-204",
    category: "Starting Motor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a21-220",
    partNumber: "A21-220",
    name: "Starting Motor — A21-220",
    category: "Starting Motor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a21-25",
    partNumber: "A21-25",
    name: "Starting Motor — A21-25",
    category: "Starting Motor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a21-26",
    partNumber: "A21-26",
    name: "Starting Motor — A21-26",
    category: "Starting Motor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a21-30",
    partNumber: "A21-30",
    name: "Starting Motor — A21-30",
    category: "Starting Motor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a21-368",
    partNumber: "A21-368",
    name: "Starting Motor — A21-368",
    category: "Starting Motor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a21-39",
    partNumber: "A21-39",
    name: "Starting Motor — A21-39",
    category: "Starting Motor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a21-5b",
    partNumber: "A21-5B",
    name: "Starting Motor — A21-5B",
    category: "Starting Motor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a23-10",
    partNumber: "A23-10",
    name: "Air Filter — A23-10",
    category: "Air Filter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a23-11",
    partNumber: "A23-11",
    name: "Air Filter — A23-11",
    category: "Air Filter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a23-12",
    partNumber: "A23-12",
    name: "Air Filter — A23-12",
    category: "Air Filter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a23-13",
    partNumber: "A23-13",
    name: "Air Filter — A23-13",
    category: "Air Filter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a23-14",
    partNumber: "A23-14",
    name: "Air Filter — A23-14",
    category: "Air Filter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a23-15",
    partNumber: "A23-15",
    name: "Air Filter — A23-15",
    category: "Air Filter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a23-16",
    partNumber: "A23-16",
    name: "Air Filter — A23-16",
    category: "Air Filter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a23-17",
    partNumber: "A23-17",
    name: "Air Filter — A23-17",
    category: "Air Filter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a23-18",
    partNumber: "A23-18",
    name: "Air Filter — A23-18",
    category: "Air Filter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a23-19",
    partNumber: "A23-19",
    name: "Air Filter — A23-19",
    category: "Air Filter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a23-20",
    partNumber: "A23-20",
    name: "Air Filter — A23-20",
    category: "Air Filter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a23-21",
    partNumber: "A23-21",
    name: "Air Filter — A23-21",
    category: "Air Filter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a23-23",
    partNumber: "A23-23",
    name: "Air Filter — A23-23",
    category: "Air Filter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a23-36",
    partNumber: "A23-36",
    name: "Air Filter — A23-36",
    category: "Air Filter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a23-4",
    partNumber: "A23-4",
    name: "Air Filter — A23-4",
    category: "Air Filter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a23-40",
    partNumber: "A23-40",
    name: "Air Filter — A23-40",
    category: "Air Filter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a23-43",
    partNumber: "A23-43",
    name: "Air Filter — A23-43",
    category: "Air Filter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a23-45",
    partNumber: "A23-45",
    name: "Air Filter — A23-45",
    category: "Air Filter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a23-4a",
    partNumber: "A23-4A",
    name: "Air Filter — A23-4A",
    category: "Air Filter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a23-62",
    partNumber: "A23-62",
    name: "Air Filter — A23-62",
    category: "Air Filter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a23-7",
    partNumber: "A23-7",
    name: "Air Filter — A23-7",
    category: "Air Filter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a23-9",
    partNumber: "A23-9",
    name: "Air Filter — A23-9",
    category: "Air Filter",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a24-208",
    partNumber: "A24-208",
    name: "Thermostat — A24-208",
    category: "Thermostat",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a24-4",
    partNumber: "A24-4",
    name: "Thermostat — A24-4",
    category: "Thermostat",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a25-12",
    partNumber: "A25-12",
    name: "Oil Pump — A25-12",
    category: "Oil Pump",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a25-13",
    partNumber: "A25-13",
    name: "Oil Pump — A25-13",
    category: "Oil Pump",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a25-15",
    partNumber: "A25-15",
    name: "Oil Pump — A25-15",
    category: "Oil Pump",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a25-16",
    partNumber: "A25-16",
    name: "Oil Pump — A25-16",
    category: "Oil Pump",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a25-19",
    partNumber: "A25-19",
    name: "Oil Pump — A25-19",
    category: "Oil Pump",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a25-20",
    partNumber: "A25-20",
    name: "Oil Pump — A25-20",
    category: "Oil Pump",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a25-21",
    partNumber: "A25-21",
    name: "Oil Pump — A25-21",
    category: "Oil Pump",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a25-22",
    partNumber: "A25-22",
    name: "Oil Pump — A25-22",
    category: "Oil Pump",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a25-23",
    partNumber: "A25-23",
    name: "Oil Pump — A25-23",
    category: "Oil Pump",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a25-28",
    partNumber: "A25-28",
    name: "Oil Pump — A25-28",
    category: "Oil Pump",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a25-29",
    partNumber: "A25-29",
    name: "Oil Pump — A25-29",
    category: "Oil Pump",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a25-30",
    partNumber: "A25-30",
    name: "Oil Pump — A25-30",
    category: "Oil Pump",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a25-31",
    partNumber: "A25-31",
    name: "Oil Pump — A25-31",
    category: "Oil Pump",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-148",
    partNumber: "A26-148",
    name: "Solenoid Valve — A26-148",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-160",
    partNumber: "A26-160",
    name: "Solenoid Valve — A26-160",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-24",
    partNumber: "A26-24",
    name: "Solenoid Valve — A26-24",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-254",
    partNumber: "A26-254",
    name: "Solenoid Valve — A26-254",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-27a",
    partNumber: "A26-27A",
    name: "Solenoid Valve — A26-27A",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-318",
    partNumber: "A26-318",
    name: "Solenoid Valve — A26-318",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-378",
    partNumber: "A26-378",
    name: "Solenoid Valve — A26-378",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-41a",
    partNumber: "A26-41A",
    name: "Solenoid Valve — A26-41A",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-42",
    partNumber: "A26-42",
    name: "Solenoid Valve — A26-42",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-43a",
    partNumber: "A26-43A",
    name: "Solenoid Valve — A26-43A",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-44",
    partNumber: "A26-44",
    name: "Solenoid Valve — A26-44",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-5",
    partNumber: "A26-5",
    name: "Solenoid Valve — A26-5",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-53",
    partNumber: "A26-53",
    name: "Solenoid Valve — Hitachi EX200-5 / ZAX200-3",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Hitachi EX200-5", "Hitachi ZAX200-3"],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-54",
    partNumber: "A26-54",
    name: "Solenoid Valve — Hitachi EX200-5",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Hitachi EX200-5"],
    notes: "OEM: 9218229 · Supplier: Kafu",
  },
  {
    id: "kafu-a26-61",
    partNumber: "A26-61",
    name: "Solenoid Valve — CAT",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Caterpillar"],
    notes: "OEM: 121-4036 · Supplier: Kafu",
  },
  {
    id: "kafu-a26-67",
    partNumber: "A26-67",
    name: "Solenoid Valve — E320C",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Caterpillar E320C"],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-67a",
    partNumber: "A26-67A",
    name: "Solenoid Valve — CAT",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Caterpillar"],
    notes: "OEM: 170-9419 · Supplier: Kafu",
  },
  {
    id: "kafu-a26-69f",
    partNumber: "A26-69F",
    name: "Solenoid Valve — A26-69F",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-71",
    partNumber: "A26-71",
    name: "Solenoid Valve — JCB 24V",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["JCB"],
    notes: "Voltage: 24V · Supplier: Kafu",
  },
  {
    id: "kafu-a26-71b",
    partNumber: "A26-71B",
    name: "Solenoid Valve — Volvo 24V",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Volvo"],
    notes: "OEM: 11418522 · Voltage: 24V · Supplier: Kafu",
  },
  {
    id: "kafu-a26-73a",
    partNumber: "A26-73A",
    name: "Solenoid Valve — CAT",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Caterpillar"],
    notes: "OEM: 225-0303 · Supplier: Kafu",
  },
  {
    id: "kafu-a26-73b",
    partNumber: "A26-73B",
    name: "Solenoid Valve — JCB",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["JCB"],
    notes: "OEM: 25/974628 · Supplier: Kafu",
  },
  {
    id: "kafu-a26-75",
    partNumber: "A26-75",
    name: "Solenoid Valve — A26-75",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-77a",
    partNumber: "A26-77A",
    name: "Solenoid Valve — Volvo",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Volvo"],
    notes: "OEM: VDE15125649 · Supplier: Kafu",
  },
  {
    id: "kafu-a26-80",
    partNumber: "A26-80",
    name: "Solenoid Valve — A26-80",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-81",
    partNumber: "A26-81",
    name: "Solenoid Valve — A26-81",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-83",
    partNumber: "A26-83",
    name: "Solenoid Valve 12V/24V",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "OEM: 3017993 · Voltage: 12V/24V · Supplier: Kafu",
  },
  {
    id: "kafu-a26-84",
    partNumber: "A26-84",
    name: "Solenoid Valve — A26-84",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-84a",
    partNumber: "A26-84A",
    name: "Solenoid Valve — A26-84A",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-86a",
    partNumber: "A26-86A",
    name: "Solenoid Valve — A26-86A",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-88a",
    partNumber: "A26-88A",
    name: "Solenoid Valve — A26-88A",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-89",
    partNumber: "A26-89",
    name: "Solenoid Valve — DH220-5",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Doosan DH220-5"],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-90",
    partNumber: "A26-90",
    name: "Solenoid Valve — A26-90",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-91",
    partNumber: "A26-91",
    name: "Solenoid Valve — A26-91",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-92",
    partNumber: "A26-92",
    name: "Solenoid Valve — A26-92",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-93",
    partNumber: "A26-93",
    name: "Solenoid Valve — A26-93",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-96",
    partNumber: "A26-96",
    name: "Solenoid Valve — A26-96",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a26-97",
    partNumber: "A26-97",
    name: "Solenoid Valve — Volvo",
    category: "Solenoid Valve",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Volvo"],
    notes: "OEM: 11709493 · Supplier: Kafu",
  },
  {
    id: "kafu-a27-46a",
    partNumber: "A27-46A",
    name: "Throttle Motor Parts — A27-46A",
    category: "Throttle Motor Parts",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Voltage: 24V · Supplier: Kafu",
  },
  {
    id: "kafu-r60-7",
    partNumber: "R60-7",
    name: "Water Temp Sensor — R60-7",
    category: "Water Temp Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-r60-9",
    partNumber: "R60-9",
    name: "Accelerator Motor — R60-9",
    category: "Accelerator Motor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "Supplier: Kafu",
  },
];

