import type { Part } from "@/lib/mock-data";

/** Kafu sections — structured paste (part #, type, OEM, machine). */
export const kafuParts: Part[] = [
  {
    id: "kafu-a01-1",
    partNumber: "A01-1",
    partNumbers: ["A01-1", "7861-93-2330"],
    name: "Revolution Sensor — KOMATSU PC200-7, PC220-7",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOMATSU PC200-7", "PC220-7"],
    notes: "OEM: 7861-93-2330 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-1a",
    partNumber: "A01-1A",
    partNumbers: ["A01-1A", "2055358"],
    name: "Revolution Sensor — HITACHI EX Series",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["HITACHI EX Series"],
    notes: "OEM: 2055358 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-1b",
    partNumber: "A01-1B",
    partNumbers: ["A01-1B", "ME844577"],
    name: "Revolution Sensor — KOMATSU PC200-6, PC200-6E",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOMATSU PC200-6", "PC200-6E"],
    notes: "OEM: ME844577 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-2",
    partNumber: "A01-2",
    partNumbers: ["A01-2", "ME845235"],
    name: "Revolution Sensor — KOMATSU PC200-3, PC200-5",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOMATSU PC200-3", "PC200-5"],
    notes: "OEM: ME845235 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-2a",
    partNumber: "A01-2A",
    partNumbers: ["A01-2A", "7819-11-2310"],
    name: "Revolution Sensor — KOMATSU WA500-1 Wheel Loader",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOMATSU WA500-1 Wheel Loader"],
    notes: "OEM: 7819-11-2310 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-2b",
    partNumber: "A01-2B",
    partNumbers: ["A01-2B", "7861-92-2330"],
    name: "Revolution Sensor — KOMATSU PC200-5, PC200-6, PC220-6 (6D102 Engine)",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOMATSU PC200-5", "PC200-6", "PC220-6 (6D102 Engine)"],
    notes: "OEM: 7861-92-2330 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-2c",
    partNumber: "A01-2C",
    partNumbers: ["A01-2C", "59841-01290"],
    name: "Revolution Sensor — KOBELCO SK200-8",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOBELCO SK200-8"],
    notes: "OEM: 59841-01290 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-3",
    partNumber: "A01-3",
    partNumbers: ["A01-3", "363-06-31121"],
    name: "Revolution Sensor — KOMATSU Engineering Systems",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOMATSU Engineering Systems"],
    notes: "OEM: 363-06-31121 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-3a",
    partNumber: "A01-3A",
    partNumbers: ["A01-3A", "PC 363-06-31121"],
    name: "Revolution Sensor — KOMATSU Master Systems Line",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOMATSU Master Systems Line"],
    notes: "OEM: PC 363-06-31121 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-4",
    partNumber: "A01-4",
    partNumbers: ["A01-4", "E2B-M30LS15-WP-B1"],
    name: "Inductive Switch Sensor — Proximity Mechanical Systems",
    category: "Inductive Switch Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Proximity Mechanical Systems"],
    notes: "OEM: E2B-M30LS15-WP-B1 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-5",
    partNumber: "A01-5",
    partNumbers: ["A01-5", "196-7973", "125-2966"],
    name: "Revolution Sensor — CATERPILLAR E320 Series Excavator",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR E320 Series Excavator"],
    notes: "OEM: 196-7973, 125-2966 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-6",
    partNumber: "A01-6",
    partNumbers: ["A01-6", "324-4131"],
    name: "Revolution Sensor — CATERPILLAR E320D Series",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR E320D Series"],
    notes: "OEM: 324-4131 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-6a",
    partNumber: "A01-6A",
    partNumbers: ["A01-6A", "51-7579"],
    name: "Revolution Sensor — CATERPILLAR E320B, E320C Series",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR E320B", "E320C Series"],
    notes: "OEM: 51-7579 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-7",
    partNumber: "A01-7",
    partNumbers: ["A01-7", "193-2550", "1-2550"],
    name: "Revolution Sensor — CATERPILLAR E329 (Φ16 Thick Housing)",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR E329 (Φ16 Thick Housing)"],
    notes: "OEM: 193-2550, 1-2550 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-7a",
    partNumber: "A01-7A",
    partNumbers: ["A01-7A", "4P-5820", "189-5746"],
    name: "Revolution Sensor — CATERPILLAR E330C, E325C (Φ19 Thick Housing)",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR E330C", "E325C (Φ19 Thick Housing)"],
    notes: "OEM: 4P-5820, 189-5746 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-7b",
    partNumber: "A01-7B",
    partNumbers: ["A01-7B", "212-3426"],
    name: "Revolution Sensor — CATERPILLAR Excavator Core",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Excavator Core"],
    notes: "OEM: 212-3426 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-8",
    partNumber: "A01-8",
    partNumbers: ["A01-8", "D04FR"],
    name: "Revolution Sensor — KOBELCO SK130-8, SK140-8",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOBELCO SK130-8", "SK140-8"],
    notes: "OEM: D04FR · Supplier: Kafu",
  },
  {
    id: "kafu-a01-9",
    partNumber: "A01-9",
    partNumbers: ["A01-9", "ME845235"],
    name: "Revolution Sensor — KOBELCO SK200-3, SK200-5",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOBELCO SK200-3", "SK200-5"],
    notes: "OEM: ME845235 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-10",
    partNumber: "A01-10",
    partNumbers: ["A01-10", "MC867505"],
    name: "Revolution Sensor — SANY Heavy Machinery Series",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["SANY Heavy Machinery Series"],
    notes: "OEM: MC867505 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-10a",
    partNumber: "A01-10A",
    partNumbers: ["A01-10A", "MC867505"],
    name: "Revolution Sensor — SANY Earthmoving Systems",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["SANY Earthmoving Systems"],
    notes: "OEM: MC867505 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-11",
    partNumber: "A01-11",
    partNumbers: ["A01-11", "59841-01290"],
    name: "Revolution Sensor — KOBELCO SK200-8, SK350-8",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOBELCO SK200-8", "SK350-8"],
    notes: "OEM: 59841-01290 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-11a",
    partNumber: "A01-11A",
    partNumbers: ["A01-11A", "SK200-8", "SK350-8"],
    name: "Revolution Sensor — KOBELCO Heavy Excavator Line",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOBELCO Heavy Excavator Line"],
    notes: "OEM: SK200-8, SK350-8 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-12",
    partNumber: "A01-12",
    partNumbers: ["A01-12", "ME755778", "9443612071"],
    name: "Fuel Pump Speed Sensor — MITSUBISHI 6D24 Injection Pump",
    category: "Fuel Pump Speed Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["MITSUBISHI 6D24 Injection Pump"],
    notes: "OEM: ME755778, 9443612071 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-12a",
    partNumber: "A01-12A",
    partNumbers: ["A01-12A", "ME755970", "9443613465"],
    name: "Fuel Pump Speed Sensor — MITSUBISHI 6D16 Diesel Pump",
    category: "Fuel Pump Speed Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["MITSUBISHI 6D16 Diesel Pump"],
    notes: "OEM: ME755970, 9443613465 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-13",
    partNumber: "A01-13",
    partNumbers: ["A01-13"],
    name: "Revolution Sensor — HITACHI EX Series Generations",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["HITACHI EX Series Generations"],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a01-14",
    partNumber: "A01-14",
    partNumbers: ["A01-14", "4265372"],
    name: "Revolution Sensor — HITACHI EX200-1, EX200-2, EX200-3",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["HITACHI EX200-1", "EX200-2", "EX200-3", "EX200-5", "EX120"],
    notes: "OEM: 4265372 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-15",
    partNumber: "A01-15",
    partNumbers: ["A01-15", "1-81510713-1"],
    name: "Revolution Sensor — ISUZU 6WG1 Engine / HITACHI ZAX450",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["ISUZU 6WG1 Engine / HITACHI ZAX450"],
    notes: "OEM: 1-81510713-1 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-16",
    partNumber: "A01-16",
    partNumbers: ["A01-16", "2547-1015"],
    name: "Revolution Sensor — DOOSAN DAEWOO DH220-5",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["DOOSAN DAEWOO DH220-5"],
    notes: "OEM: 2547-1015 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-17",
    partNumber: "A01-17",
    partNumbers: ["A01-17", "21E3-0042"],
    name: "Revolution Sensor — HYUNDAI R220-5 Excavator",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["HYUNDAI R220-5 Excavator"],
    notes: "OEM: 21E3-0042 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-18",
    partNumber: "A01-18",
    partNumbers: ["A01-18", "94340-72411"],
    name: "Revolution Sensor — HYUNDAI R225-7 Excavator",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["HYUNDAI R225-7 Excavator"],
    notes: "OEM: 94340-72411 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-19",
    partNumber: "A01-19",
    partNumbers: ["A01-19", "1-81510553-1"],
    name: "Revolution Sensor — SUMITOMO SH200A3 (ISUZU Power)",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["SUMITOMO SH200A3 (ISUZU Power)"],
    notes: "OEM: 1-81510553-1 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-20",
    partNumber: "A01-20",
    partNumbers: ["A01-20", "3034572"],
    name: "Revolution Sensor — CUMMINS K19 Engine Block",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CUMMINS K19 Engine Block"],
    notes: "OEM: 3034572 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-21",
    partNumber: "A01-21",
    partNumbers: ["A01-21", "307815", "4984223"],
    name: "Revolution Sensor — LIUGONG Material Handling Systems",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["LIUGONG Material Handling Systems"],
    notes: "OEM: 307815, 4984223 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-21a",
    partNumber: "A01-21A",
    partNumbers: ["A01-21A", "4327234"],
    name: "Revolution Sensor — CUMMINS Engine Generation",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CUMMINS Engine Generation"],
    notes: "OEM: 4327234 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-21b",
    partNumber: "A01-21B",
    partNumbers: ["A01-21B", "4327233"],
    name: "Revolution Sensor — CUMMINS Power Systems Block",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CUMMINS Power Systems Block"],
    notes: "OEM: 4327233 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-21c",
    partNumber: "A01-21C",
    partNumbers: ["A01-21C", "4327239", "3408472"],
    name: "Revolution Sensor — KOMATSU PC1250-7 / HITACHI ZAX1200",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOMATSU PC1250-7 / HITACHI ZAX1200"],
    notes: "OEM: 4327239, 3408472 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-22",
    partNumber: "A01-22",
    partNumbers: ["A01-22", "2872361"],
    name: "Revolution Sensor — LIUGONG 922D, 936D",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["LIUGONG 922D", "936D"],
    notes: "OEM: 2872361 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-23",
    partNumber: "A01-23",
    partNumbers: ["A01-23", "2872361"],
    name: "Revolution Sensor — LIUGONG 920D, 920E",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["LIUGONG 920D", "920E"],
    notes: "OEM: 2872361 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-24",
    partNumber: "A01-24",
    partNumbers: ["A01-24", "30B0202"],
    name: "Revolution Sensor — LIUGONG 907D, 908CD Compacts",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["LIUGONG 907D", "908CD Compacts"],
    notes: "OEM: 30B0202 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-25",
    partNumber: "A01-25",
    partNumbers: ["A01-25", "J213-92A-240001"],
    name: "Revolution Sensor — SUNWARD 山重 913 Excavator",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["SUNWARD 山重 913 Excavator"],
    notes: "OEM: J213-92A-240001 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-26",
    partNumber: "A01-26",
    partNumbers: ["A01-26", "RL11-61C000003AD-1"],
    name: "Revolution Sensor — FOTON LOVOL 福田雷沃 Equipment",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["FOTON LOVOL 福田雷沃 Equipment"],
    notes: "OEM: RL11-61C000003AD-1 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-27",
    partNumber: "A01-27",
    partNumbers: ["A01-27", "290-5792"],
    name: "Pressure Switch Core — CATERPILLAR Heavy Machinery Engine",
    category: "Pressure Switch Core",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Heavy Machinery Engine"],
    notes: "OEM: 290-5792 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-27a",
    partNumber: "A01-27A",
    partNumbers: ["A01-27A", "196-1185"],
    name: "Pressure Switch Core — CATERPILLAR Sensor Network Block",
    category: "Pressure Switch Core",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Sensor Network Block"],
    notes: "OEM: 196-1185 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-27b",
    partNumber: "A01-27B",
    partNumbers: ["A01-27B", "227-6744"],
    name: "Revolution Sensor — CATERPILLAR Machinery Engine System",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Machinery Engine System"],
    notes: "OEM: 227-6744 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-27c",
    partNumber: "A01-27C",
    partNumbers: ["A01-27C", "265-9033"],
    name: "Revolution Sensor — CATERPILLAR 3508, 3512 Marine/Gen Engines",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR 3508", "3512 Marine/Gen Engines"],
    notes: "OEM: 265-9033 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-27d",
    partNumber: "A01-27D",
    partNumbers: ["A01-27D", "258-4521"],
    name: "Revolution Sensor — CATERPILLAR Industrial Application Engine",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Industrial Application Engine"],
    notes: "OEM: 258-4521 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-27e",
    partNumber: "A01-27E",
    partNumbers: ["A01-27E", "504-9586"],
    name: "Revolution Sensor — CATERPILLAR Heavy Infrastructure Machinery",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Heavy Infrastructure Machinery"],
    notes: "OEM: 504-9586 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-27f",
    partNumber: "A01-27F",
    partNumbers: ["A01-27F", "253-2673"],
    name: "Revolution Sensor — CATERPILLAR General Excavator Architecture",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR General Excavator Architecture"],
    notes: "OEM: 253-2673 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-27g",
    partNumber: "A01-27G",
    partNumbers: ["A01-27G", "440-0257"],
    name: "Revolution Sensor — CATERPILLAR Mid-Tier Fleet Engine",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Mid-Tier Fleet Engine"],
    notes: "OEM: 440-0257 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-27h",
    partNumber: "A01-27H",
    partNumbers: ["A01-27H", "458-0219"],
    name: "Revolution Sensor — CATERPILLAR Processing Systems",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Processing Systems"],
    notes: "OEM: 458-0219 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-27i",
    partNumber: "A01-27I",
    partNumbers: ["A01-27I", "391-7125"],
    name: "Revolution Sensor — CATERPILLAR Modern Hydraulic Control Systems",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Modern Hydraulic Control Systems"],
    notes: "OEM: 391-7125 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-27j",
    partNumber: "A01-27J",
    partNumbers: ["A01-27J", "574-8674"],
    name: "Revolution Sensor — CATERPILLAR Compact Excavator Platform",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Compact Excavator Platform"],
    notes: "OEM: 574-8674 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-27k",
    partNumber: "A01-27K",
    partNumbers: ["A01-27K", "122-8863"],
    name: "Revolution Sensor — CATERPILLAR Legacy Structural Platforms",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Legacy Structural Platforms"],
    notes: "OEM: 122-8863 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-28",
    partNumber: "A01-28",
    partNumbers: ["A01-28", "PC 363-06-31121"],
    name: "Pressure Switch Core — YUCHAI 玉柴 Engine Platforms",
    category: "Pressure Switch Core",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["YUCHAI 玉柴 Engine Platforms"],
    notes: "OEM: PC 363-06-31121 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-29",
    partNumber: "A01-29",
    partNumbers: ["A01-29"],
    name: "Revolution Sensor — CUMMINS / YUCHAI Interface Cross-Platform CUMMINS Engine Designs",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CUMMINS / YUCHAI Interface Cross-Platform CUMMINS Engine Designs"],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a01-30",
    partNumber: "A01-30",
    partNumbers: ["A01-30", "T0411-17102"],
    name: "Revolution Sensor — YUCHAI Industrial Diesel Line",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["YUCHAI Industrial Diesel Line"],
    notes: "OEM: T0411-17102 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-31",
    partNumber: "A01-31",
    partNumbers: ["A01-31", "T0411-17103"],
    name: "Revolution Sensor — YUCHAI Heavy Machinery Engine",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["YUCHAI Heavy Machinery Engine"],
    notes: "OEM: T0411-17103 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-32",
    partNumber: "A01-32",
    partNumbers: ["A01-32", "T0411-17104"],
    name: "Revolution Sensor — YUCHAI High Displacement Engine Block",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["YUCHAI High Displacement Engine Block"],
    notes: "OEM: T0411-17104 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-33",
    partNumber: "A01-33",
    partNumbers: ["A01-33", "ZG105A"],
    name: "Revolution Sensor — SHANDONG CARTER 山东卡特 Equipment",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["SHANDONG CARTER 山东卡特 Equipment"],
    notes: "OEM: ZG105A · Supplier: Kafu",
  },
  {
    id: "kafu-a01-34",
    partNumber: "A01-34",
    partNumbers: ["A01-34", "ZG40-3", "4-16UNF Thread"],
    name: "Revolution Sensor — JONYANG 詹阳 Mid-Excavator Systems",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["JONYANG 詹阳 Mid-Excavator Systems"],
    notes: "OEM: ZG40-3, 4-16UNF Thread · Supplier: Kafu",
  },
  {
    id: "kafu-a01-35",
    partNumber: "A01-35",
    partNumbers: ["A01-35", "G220-11-5TSWS"],
    name: "Revolution Sensor — ZOOMLION 中联重科 150 Excavator",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["ZOOMLION 中联重科 150 Excavator"],
    notes: "OEM: G220-11-5TSWS · Supplier: Kafu",
  },
  {
    id: "kafu-a01-36",
    partNumber: "A01-36",
    partNumbers: ["A01-36"],
    name: "Revolution Sensor — XCMG Production Line Target XCMG 徐工 Heavy Infrastructure Machines",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["XCMG Production Line Target XCMG 徐工 Heavy Infrastructure Machines"],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a01-37",
    partNumber: "A01-37",
    partNumbers: ["A01-37"],
    name: "Revolution Sensor — PERKINS B3.3 Target Configuration Cross-Platform Engine Systems (PERKINS Power)",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["PERKINS B3.3 Target Configuration Cross-Platform Engine Systems (PERKINS Power)"],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a01-38",
    partNumber: "A01-38",
    partNumbers: ["A01-38", "Q216005"],
    name: "Revolution Sensor — Specialty Fleet Electronic Systems",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Specialty Fleet Electronic Systems"],
    notes: "OEM: Q216005 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-39",
    partNumber: "A01-39",
    partNumbers: ["A01-39", "266-8576General Infrastructure Fleet Integration"],
    name: "Revolution Sensor — 266-8576General Infrastructure Fleet Integration",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "OEM: 266-8576General Infrastructure Fleet Integration · Supplier: Kafu",
  },
  {
    id: "kafu-a01-40",
    partNumber: "A01-40",
    partNumbers: ["A01-40", "266-8576"],
    name: "Revolution Sensor — High Density Control Nodes",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["High Density Control Nodes"],
    notes: "OEM: 266-8576 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-41",
    partNumber: "A01-41",
    partNumbers: ["A01-41", "522-1643"],
    name: "Revolution Sensor — CATERPILLAR Fleet Power Systems",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Fleet Power Systems"],
    notes: "OEM: 522-1643 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-41a",
    partNumber: "A01-41A",
    partNumbers: ["A01-41A", "522-1642"],
    name: "Revolution Sensor — CATERPILLAR 980G Wheel Loader Platform",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR 980G Wheel Loader Platform"],
    notes: "OEM: 522-1642 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-42",
    partNumber: "A01-42",
    partNumbers: ["A01-42", "669 3921"],
    name: "Revolution Sensor — BOBCAT Compact Industrial Track Loader",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["BOBCAT Compact Industrial Track Loader"],
    notes: "OEM: 669 3921 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-42a",
    partNumber: "A01-42A",
    partNumbers: ["A01-42A", "449298 SystemHK450 SLX300 Track Equipment"],
    name: "Revolution Sensor — 449298 SystemHK450 SLX300 Track Equipment",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "OEM: 449298 SystemHK450 SLX300 Track Equipment · Supplier: Kafu",
  },
  {
    id: "kafu-a01-43",
    partNumber: "A01-43",
    partNumbers: ["A01-43", "668 4037"],
    name: "Revolution Sensor — BOBCAT S100, S160 Skid Steer Platforms",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["BOBCAT S100", "S160 Skid Steer Platforms"],
    notes: "OEM: 668 4037 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-43a",
    partNumber: "A01-43A",
    partNumbers: ["A01-43A", "RE287415"],
    name: "Revolution Sensor — JOHN DEERE Agricultural and Industrial Fleet",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["JOHN DEERE Agricultural and Industrial Fleet"],
    notes: "OEM: RE287415 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-43b",
    partNumber: "A01-43B",
    partNumbers: ["A01-43B", "6658260"],
    name: "Revolution Sensor — Specialty Equipment Component Platform",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Specialty Equipment Component Platform"],
    notes: "OEM: 6658260 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-44",
    partNumber: "A01-44",
    partNumbers: ["A01-44", "K19 Blocks Base"],
    name: "Revolution Sensor — CUMMINS Engine Control Grid",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CUMMINS Engine Control Grid"],
    notes: "OEM: K19 Blocks Base · Supplier: Kafu",
  },
  {
    id: "kafu-a01-45",
    partNumber: "A01-45",
    partNumbers: ["A01-45", "2868A006"],
    name: "Revolution Sensor — PERKINS Engine Power Packs",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["PERKINS Engine Power Packs"],
    notes: "OEM: 2868A006 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-46",
    partNumber: "A01-46",
    partNumbers: ["A01-46", "171-257"],
    name: "Revolution Sensor — PERKINS Industrial Generator Modules",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["PERKINS Industrial Generator Modules"],
    notes: "OEM: 171-257 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-47",
    partNumber: "A01-47",
    partNumbers: ["A01-47", "171-233"],
    name: "Revolution Sensor — PERKINS Precision Stationary Generators",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["PERKINS Precision Stationary Generators"],
    notes: "OEM: 171-233 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-48",
    partNumber: "A01-48",
    partNumbers: ["A01-48", "M16x1.5x120mm"],
    name: "Revolution Sensor — PERKINS Extended Mechanical Shaft Units",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["PERKINS Extended Mechanical Shaft Units"],
    notes: "OEM: M16x1.5x120mm · Supplier: Kafu",
  },
  {
    id: "kafu-a01-49",
    partNumber: "A01-49",
    partNumbers: ["A01-49", "M16x1.5"],
    name: "Revolution Sensor — PERKINS Threaded Crankcase Blocks",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["PERKINS Threaded Crankcase Blocks"],
    notes: "OEM: M16x1.5 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-50",
    partNumber: "A01-50",
    partNumbers: ["A01-50"],
    name: "Revolution Sensor — PERKINS Heavy Duty Generator Blocks",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["PERKINS Heavy Duty Generator Blocks"],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a01-51",
    partNumber: "A01-51",
    partNumbers: ["A01-51", "171-232"],
    name: "Revolution Sensor — PERKINS Marine and Auxiliary Power Units",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["PERKINS Marine and Auxiliary Power Units"],
    notes: "OEM: 171-232 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-52",
    partNumber: "A01-52",
    partNumbers: ["A01-52"],
    name: "Revolution Sensor — Generic Machinery Application Base",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Generic Machinery Application Base"],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a01-53",
    partNumber: "A01-53",
    partNumbers: ["A01-53", "M16x1.5"],
    name: "Revolution Sensor — Universal Machinery Sensor Harness",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Universal Machinery Sensor Harness"],
    notes: "OEM: M16x1.5 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-54",
    partNumber: "A01-54",
    partNumbers: ["A01-54", "M18x1.5"],
    name: "Revolution Sensor — High Displacement Fleet System Base",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["High Displacement Fleet System Base"],
    notes: "OEM: M18x1.5 · Supplier: Kafu",
  },
  {
    id: "kafu-a01-55",
    partNumber: "A01-55",
    partNumbers: ["A01-55", "701-80312"],
    name: "Revolution Sensor — Heavy Industrial Infrastructure Fleet",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Heavy Industrial Infrastructure Fleet"],
    notes: "OEM: 701-80312 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-1",
    partNumber: "A02-1",
    partNumbers: ["A02-1", "254-4630", "169-3300"],
    name: "Camshaft Sensor — YANMAR 4TNV94, 4TNV98 (E325C Infrastructure Cross)",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["YANMAR 4TNV94", "4TNV98 (E325C Infrastructure Cross)"],
    notes: "OEM: 254-4630, 169-3300 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-1a",
    partNumber: "A02-1A",
    partNumbers: ["A02-1A", "384-3887"],
    name: "Camshaft Sensor — Industrial Diesel Control Networks",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Industrial Diesel Control Networks"],
    notes: "OEM: 384-3887 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-1b",
    partNumber: "A02-1B",
    partNumbers: ["A02-1B", "499-9117Precision Engine Infrastructure Modules"],
    name: "Camshaft Sensor — 499-9117Precision Engine Infrastructure Modules",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "OEM: 499-9117Precision Engine Infrastructure Modules · Supplier: Kafu",
  },
  {
    id: "kafu-a02-1c",
    partNumber: "A02-1C",
    partNumbers: ["A02-1C", "481-5928Heavy Utility Equipment Engine Grids"],
    name: "Camshaft Sensor — 481-5928Heavy Utility Equipment Engine Grids",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "OEM: 481-5928Heavy Utility Equipment Engine Grids · Supplier: Kafu",
  },
  {
    id: "kafu-a02-2",
    partNumber: "A02-2",
    partNumbers: ["A02-2", "238-0120"],
    name: "Camshaft Sensor — CATERPILLAR E320D System Integration",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR E320D System Integration"],
    notes: "OEM: 238-0120 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-2a",
    partNumber: "A02-2A",
    partNumbers: ["A02-2A", "384-3888"],
    name: "Camshaft Sensor — CATERPILLAR E320D2 Engine Frame",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR E320D2 Engine Frame"],
    notes: "OEM: 384-3888 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-2b",
    partNumber: "A02-2B",
    partNumbers: ["A02-2B", "358-2398"],
    name: "Camshaft Sensor — CATERPILLAR Engine Synchronization Grid",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Engine Synchronization Grid"],
    notes: "OEM: 358-2398 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-2c",
    partNumber: "A02-2C",
    partNumbers: ["A02-2C", "358-2399"],
    name: "Camshaft Sensor — CATERPILLAR High Precision Power Plants",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR High Precision Power Plants"],
    notes: "OEM: 358-2399 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-3",
    partNumber: "A02-3",
    partNumbers: ["A02-3", "319-6491"],
    name: "Camshaft Sensor — CATERPILLAR Precision Timing Controls",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Precision Timing Controls"],
    notes: "OEM: 319-6491 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-4",
    partNumber: "A02-4",
    partNumbers: ["A02-4", "188-7513"],
    name: "Camshaft Sensor — CATERPILLAR E336 (201-6616 / 201-6617 Engines)",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR E336 (201-6616 / 201-6617 Engines)"],
    notes: "OEM: 188-7513 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-4a",
    partNumber: "A02-4A",
    partNumbers: ["A02-4A", "279-9828"],
    name: "Camshaft Sensor — CATERPILLAR E345D Heavy Duty Platform",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR E345D Heavy Duty Platform"],
    notes: "OEM: 279-9828 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-5",
    partNumber: "A02-5",
    partNumbers: ["A02-5", "201-6615"],
    name: "Camshaft Sensor — CATERPILLAR Common Core Engine Control",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Common Core Engine Control"],
    notes: "OEM: 201-6615 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-5a",
    partNumber: "A02-5A",
    partNumbers: ["A02-5A", "216-3446"],
    name: "Camshaft Sensor — CATERPILLAR Fleet Logistics Architecture",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Fleet Logistics Architecture"],
    notes: "OEM: 216-3446 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-5b",
    partNumber: "A02-5B",
    partNumbers: ["A02-5B", "204-6204"],
    name: "Camshaft Sensor — CATERPILLAR High Displacement Heavy Equipment",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR High Displacement Heavy Equipment"],
    notes: "OEM: 204-6204 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-6",
    partNumber: "A02-6",
    partNumbers: ["A02-6", "1-81510343-2"],
    name: "Flywheel Speed Sensor — SUMITOMO SH210-5 (ISUZU 6 HK1, 6BG1 Power Blocks)",
    category: "Flywheel Speed Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["SUMITOMO SH210-5 (ISUZU 6 HK1", "6BG1 Power Blocks)"],
    notes: "OEM: 1-81510343-2 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-7",
    partNumber: "A02-7",
    partNumbers: ["A02-7", "8-97240790-0"],
    name: "Revolution Sensor — ISUZU Engines / SUMITOMO Mechanical Excavators",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["ISUZU Engines / SUMITOMO Mechanical Excavators"],
    notes: "OEM: 8-97240790-0 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-8",
    partNumber: "A02-8",
    partNumbers: ["A02-8", "8-97312108-1"],
    name: "Eccentric Shaft Speed Sensor — SUMITOMO SH160 (ISUZU 4JJ1 Common Rail Block)",
    category: "Eccentric Shaft Speed Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["SUMITOMO SH160 (ISUZU 4JJ1 Common Rail Block)"],
    notes: "OEM: 8-97312108-1 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-9",
    partNumber: "A02-9",
    partNumbers: ["A02-9", "8-98014831-0"],
    name: "Camshaft Sensor — SUMITOMO SH210-5 (ISUZU 4 HK1, 6 HK1 Platforms)",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["SUMITOMO SH210-5 (ISUZU 4 HK1", "6 HK1 Platforms)"],
    notes: "OEM: 8-98014831-0 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-10",
    partNumber: "A02-10",
    partNumbers: ["A02-10", "8-97306113-1"],
    name: "Revolution Sensor — ISUZU 4 HK1, 6 HK1 Diesel Distribution Networks",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["ISUZU 4 HK1", "6 HK1 Diesel Distribution Networks"],
    notes: "OEM: 8-97306113-1 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-10a",
    partNumber: "A02-10A",
    partNumbers: ["A02-10A"],
    name: "Revolution Sensor — JCB Integration Target JCB Track Equipment (ISUZU 4 HK1 Base Power)",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["JCB Integration Target JCB Track Equipment (ISUZU 4 HK1 Base Power)"],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-11",
    partNumber: "A02-11",
    partNumbers: ["A02-11", "8-97122324-0"],
    name: "Revolution Sensor — ISUZU Fleet Power Systems Block",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["ISUZU Fleet Power Systems Block"],
    notes: "OEM: 8-97122324-0 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-12",
    partNumber: "A02-12",
    partNumbers: ["A02-12", "8-94370581-0"],
    name: "Revolution Sensor — ISUZU Mechanical Engine Blocks",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["ISUZU Mechanical Engine Blocks"],
    notes: "OEM: 8-94370581-0 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-12a",
    partNumber: "A02-12A",
    partNumbers: ["A02-12A", "8-98019024-0"],
    name: "Camshaft Sensor — ISUZU 4 HK1, 6 HK1 Global Common Rail Lines",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["ISUZU 4 HK1", "6 HK1 Global Common Rail Lines"],
    notes: "OEM: 8-98019024-0 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-13",
    partNumber: "A02-13",
    partNumbers: ["A02-13", "0118-2850"],
    name: "Revolution Sensor — VOLVO LIUGONG Excavators (DEUTZ Diesel Blocks)",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["VOLVO LIUGONG Excavators (DEUTZ Diesel Blocks)"],
    notes: "OEM: 0118-2850 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-14",
    partNumber: "A02-14",
    partNumbers: ["A02-14", "0118-2834"],
    name: "Revolution Sensor — VOLVO Construction Platforms (DEUTZ Power Units)",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["VOLVO Construction Platforms (DEUTZ Power Units)"],
    notes: "OEM: 0118-2834 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-14a",
    partNumber: "A02-14A",
    partNumbers: ["A02-14A", "VOE20450707"],
    name: "Revolution Sensor — VOLVO D3.8 Compact Excavator Platform",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["VOLVO D3.8 Compact Excavator Platform"],
    notes: "OEM: VOE20450707 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-15",
    partNumber: "A02-15",
    partNumbers: ["A02-15", "VOE20450707"],
    name: "Crankshaft Sensor — VOLVO Production Powertrain Blocks",
    category: "Crankshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["VOLVO Production Powertrain Blocks"],
    notes: "OEM: VOE20450707 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-16",
    partNumber: "A02-16",
    partNumbers: ["A02-16", "VOE20482772"],
    name: "Camshaft Sensor — VOLVO 210 Excavator (D6E Engine Frame)",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["VOLVO 210 Excavator (D6E Engine Frame)"],
    notes: "OEM: VOE20482772 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-17",
    partNumber: "A02-17",
    partNumbers: ["A02-17", "VOE20508011"],
    name: "Camshaft Sensor — VOLVO 360 Heavy Excavator Powertrain",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["VOLVO 360 Heavy Excavator Powertrain"],
    notes: "OEM: VOE20508011 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-18",
    partNumber: "A02-18",
    partNumbers: ["A02-18", "VOE20700060"],
    name: "Air Induction Sensor — VOLVO 360 Structural Exhaust Systems",
    category: "Air Induction Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["VOLVO 360 Structural Exhaust Systems"],
    notes: "OEM: VOE20700060 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-19",
    partNumber: "A02-19",
    partNumbers: ["A02-19", "4123-840", "0281002315"],
    name: "Camshaft Sensor — VOLVO 480 Mining Excavator Platform",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["VOLVO 480 Mining Excavator Platform"],
    notes: "OEM: 4123-840, 0281002315 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-20",
    partNumber: "A02-20",
    partNumbers: ["A02-20", "4921597"],
    name: "Camshaft Sensor — HYUNDAI R265-7 Earthmoving Fleet",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["HYUNDAI R265-7 Earthmoving Fleet"],
    notes: "OEM: 4921597 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-21",
    partNumber: "A02-21",
    partNumbers: ["A02-21", "4921599"],
    name: "Camshaft Sensor — HYUNDAI R265-7 Heavy Track Platform",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["HYUNDAI R265-7 Heavy Track Platform"],
    notes: "OEM: 4921599 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-22",
    partNumber: "A02-22",
    partNumbers: ["A02-22", "238-4676", "ZGAO-00651"],
    name: "Camshaft Sensor — Industrial Diesel Common Rail Networks",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Industrial Diesel Common Rail Networks"],
    notes: "OEM: 238-4676, ZGAO-00651 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-22a",
    partNumber: "A02-22A",
    partNumbers: ["A02-22A", "6754-81-9410", "D4921684"],
    name: "Camshaft Sensor — KOMATSU PC200-8 Infrastructure Excavator",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOMATSU PC200-8 Infrastructure Excavator"],
    notes: "OEM: 6754-81-9410, D4921684 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-22b",
    partNumber: "A02-22B",
    partNumbers: ["A02-22B", "6261-81-2911", "D4921686"],
    name: "Camshaft Sensor — KOMATSU PC400-8 Earthmoving Platform",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOMATSU PC400-8 Earthmoving Platform"],
    notes: "OEM: 6261-81-2911, D4921686 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-23",
    partNumber: "A02-23",
    partNumbers: ["A02-23", "6261-81-2902"],
    name: "Camshaft Sensor — KOMATSU PC400-8 Powertrain Architecture",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOMATSU PC400-8 Powertrain Architecture"],
    notes: "OEM: 6261-81-2902 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-23a",
    partNumber: "A02-23A",
    partNumbers: ["A02-23A", "5011855AA", "4921601"],
    name: "Camshaft Sensor — CUMMINS Engine Management Networks",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CUMMINS Engine Management Networks"],
    notes: "OEM: 5011855AA, 4921601 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-24",
    partNumber: "A02-24",
    partNumbers: ["A02-24", "6217-81-9210"],
    name: "Flywheel Timing Sensor — KOMATSU PC400-7 Production Excavator",
    category: "Flywheel Timing Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOMATSU PC400-7 Production Excavator"],
    notes: "OEM: 6217-81-9210 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-25",
    partNumber: "A02-25",
    partNumbers: ["A02-25", "3405529"],
    name: "Camshaft Sensor — DOOSAN DX380 Mining Fleet",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["DOOSAN DX380 Mining Fleet"],
    notes: "OEM: 3405529 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-26",
    partNumber: "A02-26",
    partNumbers: ["A02-26", "S841-01590"],
    name: "Camshaft Sensor — KOBELCO SK350-8 (HINO J08E Engine Frame)",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOBELCO SK350-8 (HINO J08E Engine Frame)"],
    notes: "OEM: S841-01590 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-26a",
    partNumber: "A02-26A",
    partNumbers: ["A02-26A", "949979-1420"],
    name: "Camshaft Sensor — HINO Diesel Power (KOBELCO Excavator Integration)",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["HINO Diesel Power (KOBELCO Excavator Integration)"],
    notes: "OEM: 949979-1420 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-27",
    partNumber: "A02-27",
    partNumbers: ["A02-27", "VA32G9000600"],
    name: "Camshaft Sensor — KOBELCO SK130-8, SK140-8 (MITSUBISHI D04FR Engine)",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOBELCO SK130-8", "SK140-8 (MITSUBISHI D04FR Engine)"],
    notes: "OEM: VA32G9000600 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-27a",
    partNumber: "A02-27A",
    partNumbers: ["A02-27A", "VA32G9000600"],
    name: "Camshaft Sensor — SANY Production Machinery Platforms",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["SANY Production Machinery Platforms"],
    notes: "OEM: VA32G9000600 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-28",
    partNumber: "A02-28",
    partNumbers: ["A02-28", "S8941-01570"],
    name: "Camshaft Sensor — KOBELCO SK200-8 (HINO J05E Engine Frame)",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOBELCO SK200-8 (HINO J05E Engine Frame)"],
    notes: "OEM: S8941-01570 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-28a",
    partNumber: "A02-28A",
    partNumbers: ["A02-28A", "1855-781C91"],
    name: "Camshaft Sensor — PERKINS Engine Power Packs",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["PERKINS Engine Power Packs"],
    notes: "OEM: 1855-781C91 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-28b",
    partNumber: "A02-28B",
    partNumbers: ["A02-28B"],
    name: "Camshaft Sensor — PERKINS Logistics and Utility Fleet Systems",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["PERKINS Logistics and Utility Fleet Systems"],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-29",
    partNumber: "A02-29",
    partNumbers: ["A02-29", "716-30123"],
    name: "Camshaft Sensor — JCB Backhoe and Tracked Excavator Networks",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["JCB Backhoe and Tracked Excavator Networks"],
    notes: "OEM: 716-30123 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-29a",
    partNumber: "A02-29A",
    partNumbers: ["A02-29A", "238-4676", "ZGAO-00651"],
    name: "Camshaft Sensor — Specialty Infrastructure Engine Formats",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Specialty Infrastructure Engine Formats"],
    notes: "OEM: 238-4676, ZGAO-00651 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-30",
    partNumber: "A02-30",
    partNumbers: ["A02-30", "JO5"],
    name: "Crankshaft Sensor — KOBELCO SK350-8 Earthmoving Base",
    category: "Crankshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOBELCO SK350-8 Earthmoving Base"],
    notes: "OEM: JO5 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-31",
    partNumber: "A02-31",
    partNumbers: ["A02-31", "VH89411E0050"],
    name: "Camshaft Timing Sensor — DOOSAN DX260-9 Excavator Powertrain",
    category: "Camshaft Timing Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["DOOSAN DX260-9 Excavator Powertrain"],
    notes: "OEM: VH89411E0050 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-32",
    partNumber: "A02-32",
    partNumbers: ["A02-32", "1319158"],
    name: "Camshaft Timing Sensor — DOOSAN DX380 SCANIA Powered Mining Fleet",
    category: "Camshaft Timing Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["DOOSAN DX380 SCANIA Powered Mining Fleet"],
    notes: "OEM: 1319158 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-32a",
    partNumber: "A02-32A",
    partNumbers: ["A02-32A", "DOOSAN DX380 SCANIA Alternative"],
    name: "Camshaft Timing Sensor — DOOSAN DX380, DX470 Mining Fleet Platforms",
    category: "Camshaft Timing Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["DOOSAN DX380", "DX470 Mining Fleet Platforms"],
    notes: "OEM: DOOSAN DX380 SCANIA Alternative · Supplier: Kafu",
  },
  {
    id: "kafu-a02-33",
    partNumber: "A02-33",
    partNumbers: ["A02-33", "KUBOTA 158557-61720"],
    name: "Camshaft Sensor — High-Speed Compact Diesel Systems",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["High-Speed Compact Diesel Systems"],
    notes: "OEM: KUBOTA 158557-61720 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-34",
    partNumber: "A02-34",
    partNumbers: ["A02-34"],
    name: "Crankshaft Sensor — KOBELCO Heavy Excavator Platforms",
    category: "Crankshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOBELCO Heavy Excavator Platforms"],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a02-35",
    partNumber: "A02-35",
    partNumbers: ["A02-35", "4M50"],
    name: "Camshaft Sensor — KATO 加藤 HD820-5 Industrial Excavator",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KATO 加藤 HD820-5 Industrial Excavator"],
    notes: "OEM: 4M50 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-36",
    partNumber: "A02-36",
    partNumbers: ["A02-36", "11442694"],
    name: "Camshaft Sensor — LIEBHERR 利勃海尔 Construction Equipment",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["LIEBHERR 利勃海尔 Construction Equipment"],
    notes: "OEM: 11442694 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-37",
    partNumber: "A02-37",
    partNumbers: ["A02-37", "RE51944"],
    name: "Camshaft Sensor — JOHN DEERE Agricultural Tractor & Forestry Fleet",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["JOHN DEERE Agricultural Tractor & Forestry Fleet"],
    notes: "OEM: RE51944 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-38",
    partNumber: "A02-38",
    partNumbers: ["A02-38", "RE295936"],
    name: "Camshaft Sensor — JOHN DEERE Industrial Material Handling Grids",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["JOHN DEERE Industrial Material Handling Grids"],
    notes: "OEM: RE295936 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-39",
    partNumber: "A02-39",
    partNumbers: ["A02-39", "V836866392"],
    name: "Revolution Sensor — Heavy Industrial Machinery Architecture",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Heavy Industrial Machinery Architecture"],
    notes: "OEM: V836866392 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-40",
    partNumber: "A02-40",
    partNumbers: ["A02-40", "4327230"],
    name: "Revolution Sensor — CUMMINS Global Industrial Powertrains",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CUMMINS Global Industrial Powertrains"],
    notes: "OEM: 4327230 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-41",
    partNumber: "A02-41",
    partNumbers: ["A02-41", "5H911-42622"],
    name: "Revolution Sensor — KUBOTA 久保田 Compact Utility Machinery",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KUBOTA 久保田 Compact Utility Machinery"],
    notes: "OEM: 5H911-42622 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-42",
    partNumber: "A02-42",
    partNumbers: ["A02-42", "T1060-18660"],
    name: "Revolution Sensor — KUBOTA Compact Industrial Excavators",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KUBOTA Compact Industrial Excavators"],
    notes: "OEM: T1060-18660 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-43",
    partNumber: "A02-43",
    partNumbers: ["A02-43", "458-6031"],
    name: "Revolution Sensor — DOOSAN DX800 Ultra-Heavy Mining Excavator",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["DOOSAN DX800 Ultra-Heavy Mining Excavator"],
    notes: "OEM: 458-6031 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-44",
    partNumber: "A02-44",
    partNumbers: ["A02-44", "R901414438", "458-6031"],
    name: "Camshaft Sensor — REXROTH 力士乐 Electronic Pump Control Networks",
    category: "Camshaft Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["REXROTH 力士乐 Electronic Pump Control Networks"],
    notes: "OEM: R901414438, 458-6031 · Supplier: Kafu",
  },
  {
    id: "kafu-a02-45",
    partNumber: "A02-45",
    partNumbers: ["A02-45", "716", "D2727 Lead Layout"],
    name: "Revolution Sensor — JCB Construction and Logistics Equipment",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["JCB Construction and Logistics Equipment"],
    notes: "OEM: 716, D2727 Lead Layout · Supplier: Kafu",
  },
  {
    id: "kafu-a02-46",
    partNumber: "A02-46",
    partNumbers: ["A02-46", "716", "D2729 Lead Layout"],
    name: "Revolution Sensor — JCB Heavy Duty Structural Handlers",
    category: "Revolution Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["JCB Heavy Duty Structural Handlers"],
    notes: "OEM: 716, D2729 Lead Layout · Supplier: Kafu",
  },
  {
    id: "kafu-a02-47",
    partNumber: "A02-47",
    partNumbers: ["A02-47", "418-18-31502"],
    name: "Speed Sensor Array — KOMATSU WA150-5, WA20L-5 Compact Wheel Loaders",
    category: "Speed Sensor Array",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOMATSU WA150-5", "WA20L-5 Compact Wheel Loaders"],
    notes: "OEM: 418-18-31502 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-1",
    partNumber: "A03-1",
    partNumbers: ["A03-1", "8-12146830-0"],
    name: "Air Pressure Switch — ISUZU Diesel Engines / Global Fleet Trucks",
    category: "Air Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["ISUZU Diesel Engines / Global Fleet Trucks"],
    notes: "OEM: 8-12146830-0 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-2",
    partNumber: "A03-2",
    partNumbers: ["A03-2", "20450095"],
    name: "Intake Temperature Sensor — VOLVO Construction Platforms (Early Series)",
    category: "Intake Temperature Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["VOLVO Construction Platforms (Early Series)"],
    notes: "OEM: 20450095 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-3",
    partNumber: "A03-3",
    partNumbers: ["A03-3", "4076493", "6261-81-1900"],
    name: "Manifold Air Pressure Sensor — KOMATSU PC200-8 Infrastructure Excavator",
    category: "Manifold Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOMATSU PC200-8 Infrastructure Excavator"],
    notes: "OEM: 4076493, 6261-81-1900 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-4",
    partNumber: "A03-4",
    partNumbers: ["A03-4", "VOE 20450693"],
    name: "Air Intake Sensor — VOLVO Heavy Equipment Engines",
    category: "Air Intake Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["VOLVO Heavy Equipment Engines"],
    notes: "OEM: VOE 20450693 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-5",
    partNumber: "A03-5",
    partNumbers: ["A03-5", "4921322", "6754-81-2701"],
    name: "Manifold Air Pressure Sensor — KOMATSU PC200-8 Powertrain Architecture",
    category: "Manifold Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOMATSU PC200-8 Powertrain Architecture"],
    notes: "OEM: 4921322, 6754-81-2701 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-5a",
    partNumber: "A03-5A",
    partNumbers: ["A03-5A", "8-97601-9670"],
    name: "Air Intake Sensor — HITACHI Excavator Engine Network",
    category: "Air Intake Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["HITACHI Excavator Engine Network"],
    notes: "OEM: 8-97601-9670 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-6",
    partNumber: "A03-6",
    partNumbers: ["A03-6", "0281002566", "0281002576"],
    name: "Air Intake Sensor — VOLVO 210 Excavator Powertrain Grid",
    category: "Air Intake Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["VOLVO 210 Excavator Powertrain Grid"],
    notes: "OEM: 0281002566, 0281002576 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-6a",
    partNumber: "A03-6A",
    partNumbers: ["A03-6A", "22422785"],
    name: "Air Intake Sensor — VOLVO Infrastructure Machinery Systems",
    category: "Air Intake Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["VOLVO Infrastructure Machinery Systems"],
    notes: "OEM: 22422785 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-6b",
    partNumber: "A03-6B",
    partNumbers: ["A03-6B", "24527125"],
    name: "Air Intake Sensor — VOLVO Material Handling Fleets",
    category: "Air Intake Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["VOLVO Material Handling Fleets"],
    notes: "OEM: 24527125 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-7",
    partNumber: "A03-7",
    partNumbers: ["A03-7", "4076493"],
    name: "Air Pressure Sensor — CUMMINS Engine Electronic Management",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CUMMINS Engine Electronic Management"],
    notes: "OEM: 4076493 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-8",
    partNumber: "A03-8",
    partNumbers: ["A03-8", "441050080"],
    name: "Air Intake Sensor — VOLVO Power Systems Infrastructure",
    category: "Air Intake Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["VOLVO Power Systems Infrastructure"],
    notes: "OEM: 441050080 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-9",
    partNumber: "A03-9",
    partNumbers: ["A03-9", "21304786", "22181342"],
    name: "Vacuum Pressure Switch — VOLVO EC210, EC240, EC290",
    category: "Vacuum Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["VOLVO EC210", "EC240", "EC290", "EC360 Series"],
    notes: "OEM: 21304786, 22181342 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-9a",
    partNumber: "A03-9A",
    partNumbers: ["A03-9A", "15038313"],
    name: "Air Intake Sensor — VOLVO Industrial Diesel Power Packs",
    category: "Air Intake Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["VOLVO Industrial Diesel Power Packs"],
    notes: "OEM: 15038313 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-9b",
    partNumber: "A03-9B",
    partNumbers: ["A03-9B", "22172068"],
    name: "Air Intake Sensor — VOLVO Utility Infrastructure Equipment",
    category: "Air Intake Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["VOLVO Utility Infrastructure Equipment"],
    notes: "OEM: 22172068 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-10",
    partNumber: "A03-10",
    partNumbers: ["A03-10", "20542128"],
    name: "Air Intake Sensor — VOLVO EC480 Heavy Mining Excavator",
    category: "Air Intake Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["VOLVO EC480 Heavy Mining Excavator"],
    notes: "OEM: 20542128 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-11",
    partNumber: "A03-11",
    partNumbers: ["A03-11", "208935035"],
    name: "Air Intake Sensor — VOLVO Electronic Engine Integration",
    category: "Air Intake Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["VOLVO Electronic Engine Integration"],
    notes: "OEM: 208935035 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-11a",
    partNumber: "A03-11A",
    partNumbers: ["A03-11A", "208935036"],
    name: "Air Intake Sensor — VOLVO Advanced Emissions Fleet Units",
    category: "Air Intake Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["VOLVO Advanced Emissions Fleet Units"],
    notes: "OEM: 208935036 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-11b",
    partNumber: "A03-11B",
    partNumbers: ["A03-11B", "21442662"],
    name: "Air Intake Sensor — VOLVO Modernized Heavy Tracked Fleet",
    category: "Air Intake Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["VOLVO Modernized Heavy Tracked Fleet"],
    notes: "OEM: 21442662 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-12",
    partNumber: "A03-12",
    partNumbers: ["A03-12", "266-0136"],
    name: "Air Pressure Sensor — CATERPILLAR 312D Tier-Compliant Excavators",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR 312D Tier-Compliant Excavators"],
    notes: "OEM: 266-0136 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-12a",
    partNumber: "A03-12A",
    partNumbers: ["A03-12A", "381-9064"],
    name: "Air Pressure Sensor — CATERPILLAR Industrial Infrastructure Group",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Industrial Infrastructure Group"],
    notes: "OEM: 381-9064 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-12b",
    partNumber: "A03-12B",
    partNumbers: ["A03-12B", "21304786", "22181342"],
    name: "Air Pressure Sensor — VOLVO General Fleet Logistics Platforms",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["VOLVO General Fleet Logistics Platforms"],
    notes: "OEM: 21304786, 22181342 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-12c",
    partNumber: "A03-12C",
    partNumbers: ["A03-12C", "107-8618"],
    name: "Air Temp Sensor — Cross-Platform Fleet Engine Intake Manifolds",
    category: "Air Temp Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Cross-Platform Fleet Engine Intake Manifolds"],
    notes: "OEM: 107-8618 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-13",
    partNumber: "A03-13",
    partNumbers: ["A03-13", "7861-91-1420"],
    name: "Air Pressure Sensor — KOMATSU PC200-7 Machinery Platform",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOMATSU PC200-7 Machinery Platform"],
    notes: "OEM: 7861-91-1420 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-13a",
    partNumber: "A03-13A",
    partNumbers: ["A03-13A", "002254"],
    name: "Air Pressure Sensor — Universal Fixed-Plant and Fleet Diesel Engines",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Universal Fixed-Plant and Fleet Diesel Engines"],
    notes: "OEM: 002254 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-14",
    partNumber: "A03-14",
    partNumbers: ["A03-14"],
    name: "Air Intake Sensor — HITACHI Production Spec HITACHI EX, ZAX Excavator Series",
    category: "Air Intake Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["HITACHI Production Spec HITACHI EX", "ZAX Excavator Series"],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-14a",
    partNumber: "A03-14A",
    partNumbers: ["A03-14A", "381-9064"],
    name: "Air Intake Sensor — CATERPILLAR Excavator Operations Control",
    category: "Air Intake Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Excavator Operations Control"],
    notes: "OEM: 381-9064 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-15",
    partNumber: "A03-15",
    partNumbers: ["A03-15", "PC200-7 Harness"],
    name: "AC Pressure Switch — KOMATSU Fleet Cabin Environment Blocks",
    category: "AC Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOMATSU Fleet Cabin Environment Blocks"],
    notes: "OEM: PC200-7 Harness · Supplier: Kafu",
  },
  {
    id: "kafu-a03-15a",
    partNumber: "A03-15A",
    partNumbers: ["A03-15A", "PC200-8"],
    name: "Air Pressure Switch — KOMATSU Powertrain Diagnostic Systems",
    category: "Air Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOMATSU Powertrain Diagnostic Systems"],
    notes: "OEM: PC200-8 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-16",
    partNumber: "A03-16",
    partNumbers: ["A03-16", "SH200"],
    name: "Air Alarm Sensor — SUMITOMO Excavator System Protection Networks",
    category: "Air Alarm Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["SUMITOMO Excavator System Protection Networks"],
    notes: "OEM: SH200 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-17",
    partNumber: "A03-17",
    partNumbers: ["A03-17", "6261-81-2600"],
    name: "Air Pressure Sensor — KOMATSU PC400-8 Heavy Utility Machinery",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOMATSU PC400-8 Heavy Utility Machinery"],
    notes: "OEM: 6261-81-2600 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-18",
    partNumber: "A03-18",
    partNumbers: ["A03-18", "1MPP2-1"],
    name: "Differential Pressure Sensor — YUCHAI Design CUMMINS / YUCHAI Advanced Exhaust Networks",
    category: "Differential Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["YUCHAI Design CUMMINS / YUCHAI Advanced Exhaust Networks"],
    notes: "OEM: 1MPP2-1 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-18a",
    partNumber: "A03-18A",
    partNumbers: ["A03-18A", "314-9772 ConfigurationFleet Emissions Monitoring Platforms"],
    name: "Differential Pressure Sensor — 314-9772 ConfigurationFleet Emissions Monitoring Platforms",
    category: "Differential Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "OEM: 314-9772 ConfigurationFleet Emissions Monitoring Platforms · Supplier: Kafu",
  },
  {
    id: "kafu-a03-19",
    partNumber: "A03-19",
    partNumbers: ["A03-19", "VH893901080A", "ZAX200-3"],
    name: "Barometric Pressure Sensor — HITACHI ZAX200-3 (ISUZU Power / KOBELCO SK200-8 Cross)",
    category: "Barometric Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["HITACHI ZAX200-3 (ISUZU Power / KOBELCO SK200-8 Cross)"],
    notes: "OEM: VH893901080A, ZAX200-3 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-20",
    partNumber: "A03-20",
    partNumbers: ["A03-20", "8-98121697-0"],
    name: "Air Intake Sensor — HITACHI ZAX490-5A (ISUZU 6UZ1 Engine Frame)",
    category: "Air Intake Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["HITACHI ZAX490-5A (ISUZU 6UZ1 Engine Frame)"],
    notes: "OEM: 8-98121697-0 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-21",
    partNumber: "A03-21",
    partNumbers: ["A03-21", "8-98065377-0 Control"],
    name: "Air Intake Sensor — ISUZU Industrial Common Rail Diesel Engines",
    category: "Air Intake Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["ISUZU Industrial Common Rail Diesel Engines"],
    notes: "OEM: 8-98065377-0 Control · Supplier: Kafu",
  },
  {
    id: "kafu-a03-22",
    partNumber: "A03-22",
    partNumbers: ["A03-22", "DX380"],
    name: "Intake Pressure Sensor — SCANIA System Base DOOSAN DX380 Mining Fleet (SCANIA Engine Frame)",
    category: "Intake Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["SCANIA System Base DOOSAN DX380 Mining Fleet (SCANIA Engine Frame)"],
    notes: "OEM: DX380 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-23",
    partNumber: "A03-23",
    partNumbers: ["A03-23", "4902720"],
    name: "Intake Pressure Sensor — CUMMINS Global Fleet Industrial Power Blocks",
    category: "Intake Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CUMMINS Global Fleet Industrial Power Blocks"],
    notes: "OEM: 4902720 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-24",
    partNumber: "A03-24",
    partNumbers: ["A03-24", "SK210-10 Module"],
    name: "Barometric Pressure Sensor — YUCHAI Powered KOBELCO SK210-10 Fleets",
    category: "Barometric Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["YUCHAI Powered KOBELCO SK210-10 Fleets"],
    notes: "OEM: SK210-10 Module · Supplier: Kafu",
  },
  {
    id: "kafu-a03-25",
    partNumber: "A03-25",
    partNumbers: ["A03-25"],
    name: "Intake Pressure Sensor — John Deere Technical Spec JOHN DEERE Agricultural and Industrial Engines",
    category: "Intake Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["John Deere Technical Spec JOHN DEERE Agricultural and Industrial Engines"],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-25a",
    partNumber: "A03-25A",
    partNumbers: ["A03-25A", "129978-12700"],
    name: "Intake Pressure Sensor — High Reliability Utility Fleet Engines",
    category: "Intake Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["High Reliability Utility Fleet Engines"],
    notes: "OEM: 129978-12700 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-26",
    partNumber: "A03-26",
    partNumbers: ["A03-26", "6261-81-2700 Heavy Grid"],
    name: "Air Pressure Sensor — KOMATSU PC400-8 Mining and Earthmoving Fleets",
    category: "Air Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOMATSU PC400-8 Mining and Earthmoving Fleets"],
    notes: "OEM: 6261-81-2700 Heavy Grid · Supplier: Kafu",
  },
  {
    id: "kafu-a03-27",
    partNumber: "A03-27",
    partNumbers: ["A03-27", "4984590"],
    name: "Air Intake Sensor — KOMATSU PC350-10 Advanced Earthmover",
    category: "Air Intake Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOMATSU PC350-10 Advanced Earthmover"],
    notes: "OEM: 4984590 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-28",
    partNumber: "A03-28",
    partNumbers: ["A03-28", "266-1466"],
    name: "Sensor Cable Assembly — Specialized Fleet Electronic Wiring Grids",
    category: "Sensor Cable Assembly",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Specialized Fleet Electronic Wiring Grids"],
    notes: "OEM: 266-1466 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-29",
    partNumber: "A03-29",
    partNumbers: ["A03-29", "266-1467 Sealed UnitHeavy Duty Machinery Wiring Frameworks"],
    name: "Sensor Cable Assembly — 266-1467 Sealed UnitHeavy Duty Machinery Wiring Frameworks",
    category: "Sensor Cable Assembly",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "OEM: 266-1467 Sealed UnitHeavy Duty Machinery Wiring Frameworks · Supplier: Kafu",
  },
  {
    id: "kafu-a03-29a",
    partNumber: "A03-29A",
    partNumbers: ["A03-29A", "266-1468"],
    name: "Sensor Cable Assembly — High Stress Engine Bay Diagnostic Systems",
    category: "Sensor Cable Assembly",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["High Stress Engine Bay Diagnostic Systems"],
    notes: "OEM: 266-1468 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-30",
    partNumber: "A03-30",
    partNumbers: ["A03-30", "266-1475 Armored LeadHeavy Construction Machinery Harness Modules"],
    name: "Sensor Cable Assembly — 266-1475 Armored LeadHeavy Construction Machinery Harness Modules",
    category: "Sensor Cable Assembly",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "OEM: 266-1475 Armored LeadHeavy Construction Machinery Harness Modules · Supplier: Kafu",
  },
  {
    id: "kafu-a03-31",
    partNumber: "A03-31",
    partNumbers: ["A03-31", "266-1477"],
    name: "Sensor Cable Assembly — Precision Sensor Interconnect Systems",
    category: "Sensor Cable Assembly",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Precision Sensor Interconnect Systems"],
    notes: "OEM: 266-1477 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-32",
    partNumber: "A03-32",
    partNumbers: ["A03-32", "266-1478"],
    name: "Sensor Cable Assembly — Logistics and Ground Engineering Equipment",
    category: "Sensor Cable Assembly",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Logistics and Ground Engineering Equipment"],
    notes: "OEM: 266-1478 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-33",
    partNumber: "A03-33",
    partNumbers: ["A03-33", "266-1481 Interface LeadIndustrial Infrastructure Support Systems"],
    name: "Sensor Cable Assembly — 266-1481 Interface LeadIndustrial Infrastructure Support Systems",
    category: "Sensor Cable Assembly",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "OEM: 266-1481 Interface LeadIndustrial Infrastructure Support Systems · Supplier: Kafu",
  },
  {
    id: "kafu-a03-34",
    partNumber: "A03-34",
    partNumbers: ["A03-34", "266-2337"],
    name: "Sensor Cable Assembly — Field Infrastructure Operations Fleet",
    category: "Sensor Cable Assembly",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Field Infrastructure Operations Fleet"],
    notes: "OEM: 266-2337 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-35",
    partNumber: "A03-35",
    partNumbers: ["A03-35", "266-1484"],
    name: "Sensor Cable Assembly — Multi-Function Infrastructure Support Vehicles",
    category: "Sensor Cable Assembly",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Multi-Function Infrastructure Support Vehicles"],
    notes: "OEM: 266-1484 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-36",
    partNumber: "A03-36",
    partNumbers: ["A03-36", "266-1492 Base UnitHeavy Utility Fleet Asset Monitoring"],
    name: "Sensor Cable Assembly — 266-1492 Base UnitHeavy Utility Fleet Asset Monitoring",
    category: "Sensor Cable Assembly",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "OEM: 266-1492 Base UnitHeavy Utility Fleet Asset Monitoring · Supplier: Kafu",
  },
  {
    id: "kafu-a03-37",
    partNumber: "A03-37",
    partNumbers: ["A03-37", "269-1983"],
    name: "Angular Position Sensor — Hydraulic Articulation Tracking Systems",
    category: "Angular Position Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Hydraulic Articulation Tracking Systems"],
    notes: "OEM: 269-1983 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-38",
    partNumber: "A03-38",
    partNumbers: ["A03-38", "204-7949"],
    name: "Angular Position Sensor — Extreme Environment Position Feedback Units",
    category: "Angular Position Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Extreme Environment Position Feedback Units"],
    notes: "OEM: 204-7949 · Supplier: Kafu",
  },
  {
    id: "kafu-a03-39",
    partNumber: "A03-39",
    partNumbers: ["A03-39", "266-1473 Multi-AxisHeavy Rigging and Earthmoving Crane Arms"],
    name: "Angular Position Sensor — 266-1473 Multi-AxisHeavy Rigging and Earthmoving Crane Arms",
    category: "Angular Position Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "OEM: 266-1473 Multi-AxisHeavy Rigging and Earthmoving Crane Arms · Supplier: Kafu",
  },
  {
    id: "kafu-a03-40",
    partNumber: "A03-40",
    partNumbers: ["A03-40"],
    name: "Rotary Switch Sensor — Cabin Interior Control Unit Fleet Operator Console Interface Modules",
    category: "Rotary Switch Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Cabin Interior Control Unit Fleet Operator Console Interface Modules"],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a03-41",
    partNumber: "A03-41",
    partNumbers: ["A03-41"],
    name: "Door Courtesy Lamp Switch — Cockpit Frame Integration Universal Excavator and Loader Cab Systems",
    category: "Door Courtesy Lamp Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Cockpit Frame Integration Universal Excavator and Loader Cab Systems"],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-1",
    partNumber: "A04-1",
    partNumbers: ["A04-1", "EX200-5"],
    name: "Oil Pressure Switch — HITACHI EX200-5 Excavator Hydraulic System",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["HITACHI EX200-5 Excavator Hydraulic System"],
    notes: "OEM: EX200-5 · Supplier: Kafu",
  },
  {
    id: "kafu-a04-2",
    partNumber: "A04-2",
    partNumbers: ["A04-2", "6732-81-3140", "08073-10505"],
    name: "Oil Pressure Switch — KOMATSU PC200-6 Infrastructure Machine",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOMATSU PC200-6 Infrastructure Machine"],
    notes: "OEM: 6732-81-3140, 08073-10505 · Supplier: Kafu",
  },
  {
    id: "kafu-a04-3",
    partNumber: "A04-3",
    partNumbers: ["A04-3", "4JG1"],
    name: "Oil Pressure Switch — YANMAR 4JG1 Powered Compact Equipment",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["YANMAR 4JG1 Powered Compact Equipment"],
    notes: "OEM: 4JG1 · Supplier: Kafu",
  },
  {
    id: "kafu-a04-4",
    partNumber: "A04-4",
    partNumbers: ["A04-4", "8-98086433-0 Core"],
    name: "Oil Pressure Switch — ISUZU 4-Cylinder Industrial Diesel Platforms",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["ISUZU 4-Cylinder Industrial Diesel Platforms"],
    notes: "OEM: 8-98086433-0 Core · Supplier: Kafu",
  },
  {
    id: "kafu-a04-5",
    partNumber: "A04-5",
    partNumbers: ["A04-5", "6732-81-3140", "08073-10505"],
    name: "Oil Pressure Switch — HITACHI EX200-5 Dual Terminal Base Variant",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["HITACHI EX200-5 Dual Terminal Base Variant"],
    notes: "OEM: 6732-81-3140, 08073-10505 · Supplier: Kafu",
  },
  {
    id: "kafu-a04-6",
    partNumber: "A04-6",
    partNumbers: ["A04-6"],
    name: "Oil Pressure Switch — YANMAR Core Technical Spec YANMAR Industrial Utility Fleet Power Units",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["YANMAR Core Technical Spec YANMAR Industrial Utility Fleet Power Units"],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-6a",
    partNumber: "A04-6A",
    partNumbers: ["A04-6A", "7W1238 High Output GroupHeavy Duty Stationary Power Plant Modules"],
    name: "Oil Pressure Sensor — 7W1238 High Output GroupHeavy Duty Stationary Power Plant Modules",
    category: "Oil Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: [],
    notes: "OEM: 7W1238 High Output GroupHeavy Duty Stationary Power Plant Modules · Supplier: Kafu",
  },
  {
    id: "kafu-a04-7",
    partNumber: "A04-7",
    partNumbers: ["A04-7"],
    name: "Oil Pressure Sensor — Universal Block ArchitectureInfrastructure Machinery Fleet Support Units",
    category: "Oil Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Universal Block ArchitectureInfrastructure Machinery Fleet Support Units"],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-7a",
    partNumber: "A04-7A",
    partNumbers: ["A04-7A"],
    name: "Oil Pressure Sensor — Universal Block Variant B Ground Logistics Fleet Power Frameworks",
    category: "Oil Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Universal Block Variant B Ground Logistics Fleet Power Frameworks"],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-7b",
    partNumber: "A04-7B",
    partNumbers: ["A04-7B"],
    name: "Oil Pressure Sensor — Universal Block Variant CHeavy Machinery Fluid Protection Networks",
    category: "Oil Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["Universal Block Variant CHeavy Machinery Fluid Protection Networks"],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-8",
    partNumber: "A04-8",
    partNumbers: ["A04-8", "266-0210", "51-8005", "3451-40200"],
    name: "Oil Pressure Sensor — CATERPILLAR E320C Excavator Powertrain Grid",
    category: "Oil Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR E320C Excavator Powertrain Grid"],
    notes: "OEM: 266-0210, 51-8005, 3451-40200 · Supplier: Kafu",
  },
  {
    id: "kafu-a04-9",
    partNumber: "A04-9",
    partNumbers: ["A04-9"],
    name: "Oil Pressure Switch — YANMAR / KOBELCO Engine Frame KOBELCO SK230-6 (YANMAR Industrial Diesel Power)",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["YANMAR / KOBELCO Engine Frame KOBELCO SK230-6 (YANMAR Industrial Diesel Power)"],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-9a",
    partNumber: "A04-9A",
    partNumbers: ["A04-9A", "418-43-37681"],
    name: "Mechanical Pressure Switch — KOMATSU WA380-6 Heavy Duty Wheel Loader",
    category: "Mechanical Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["KOMATSU WA380-6 Heavy Duty Wheel Loader"],
    notes: "OEM: 418-43-37681 · Supplier: Kafu",
  },
  {
    id: "kafu-a04-9b",
    partNumber: "A04-9B",
    partNumbers: ["A04-9B"],
    name: "Oil Pressure Switch — DAEWOO DOOSAN Core Line Spec DOOSAN Heavy Infrastructure Machinery Fleet",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["DAEWOO DOOSAN Core Line Spec DOOSAN Heavy Infrastructure Machinery Fleet"],
    notes: "Supplier: Kafu",
  },
  {
    id: "kafu-a04-10",
    partNumber: "A04-10",
    partNumbers: ["A04-10", "83530E0220"],
    name: "Oil Pressure Switch — HINO Standard KOBELCO SK200-8, SK350-8 (HINO J05, J08E Engines)",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["HINO Standard KOBELCO SK200-8", "SK350-8 (HINO J05", "J08E Engines)"],
    notes: "OEM: 83530E0220 · Supplier: Kafu",
  },
  {
    id: "kafu-a04-11",
    partNumber: "A04-11",
    partNumbers: ["A04-11", "6BD1"],
    name: "Oil Pressure Switch — HITACHI EX200-1, EX200-2, EX200-3",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["HITACHI EX200-1", "EX200-2", "EX200-3", "EX200-5"],
    notes: "OEM: 6BD1 · Supplier: Kafu",
  },
  {
    id: "kafu-a04-12",
    partNumber: "A04-12",
    partNumbers: ["A04-12", "6BG1"],
    name: "Oil Pressure Switch — ISUZU 6BG1 Powered Industrial Fleet Assets",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["ISUZU 6BG1 Powered Industrial Fleet Assets"],
    notes: "OEM: 6BG1 · Supplier: Kafu",
  },
  {
    id: "kafu-a04-13",
    partNumber: "A04-13",
    partNumbers: ["A04-13", "8-98027456-0", "499000-7341"],
    name: "Oil Pressure Switch — HITACHI ZAX330-3 (ISUZU 6 HK1 Engine Frame)",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["HITACHI ZAX330-3 (ISUZU 6 HK1 Engine Frame)"],
    notes: "OEM: 8-98027456-0, 499000-7341 · Supplier: Kafu",
  },
  {
    id: "kafu-a04-14",
    partNumber: "A04-14",
    partNumbers: ["A04-14", "MD176361"],
    name: "Air System Pressure Switch — MITSUBISHI 4M50 Powered Fleet Machinery",
    category: "Air System Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["MITSUBISHI 4M50 Powered Fleet Machinery"],
    notes: "OEM: MD176361 · Supplier: Kafu",
  },
  {
    id: "kafu-a04-15",
    partNumber: "A04-15",
    partNumbers: ["A04-15", "161-1703"],
    name: "Oil Pressure Switch — CATERPILLAR Earthmoving Powertrain Grids",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Earthmoving Powertrain Grids"],
    notes: "OEM: 161-1703 · Supplier: Kafu",
  },
  {
    id: "kafu-a04-16",
    partNumber: "A04-16",
    partNumbers: ["A04-16", "161-1704", "04-0249A"],
    name: "Fluid Pressure Sensor — CATERPILLAR Industrial Infrastructure Blocks",
    category: "Fluid Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Industrial Infrastructure Blocks"],
    notes: "OEM: 161-1704, 04-0249A · Supplier: Kafu",
  },
  {
    id: "kafu-a04-17",
    partNumber: "A04-17",
    partNumbers: ["A04-17", "161-1705-04"],
    name: "Fluid Pressure Sensor — CATERPILLAR General Engineering Asset Platforms",
    category: "Fluid Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR General Engineering Asset Platforms"],
    notes: "OEM: 161-1705-04 · Supplier: Kafu",
  },
  {
    id: "kafu-a04-18",
    partNumber: "A04-18",
    partNumbers: ["A04-18", "194-6722"],
    name: "Oil Pressure Switch — CATERPILLAR Processing Plant Logistics Fleet",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Processing Plant Logistics Fleet"],
    notes: "OEM: 194-6722 · Supplier: Kafu",
  },
  {
    id: "kafu-a04-18a",
    partNumber: "A04-18A",
    partNumbers: ["A04-18A", "3116", "131-9203"],
    name: "Oil Pressure Switch — CATERPILLAR 3116 Mechanical Fuel Engine Lines",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR 3116 Mechanical Fuel Engine Lines"],
    notes: "OEM: 3116, 131-9203 · Supplier: Kafu",
  },
  {
    id: "kafu-a04-18b",
    partNumber: "A04-18B",
    partNumbers: ["A04-18B", "459-2584", "459-2597"],
    name: "Oil Pressure Sensor — CATERPILLAR Civil Engineering Power Grids",
    category: "Oil Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Civil Engineering Power Grids"],
    notes: "OEM: 459-2584, 459-2597 · Supplier: Kafu",
  },
  {
    id: "kafu-a04-18c",
    partNumber: "A04-18C",
    partNumbers: ["A04-18C", "459-2595"],
    name: "Oil Pressure Sensor — CATERPILLAR High Displacement Earthmoving Units",
    category: "Oil Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR High Displacement Earthmoving Units"],
    notes: "OEM: 459-2595 · Supplier: Kafu",
  },
  {
    id: "kafu-a04-18e",
    partNumber: "A04-18E",
    partNumbers: ["A04-18E", "421-06-35111"],
    name: "Oil Pressure Sensor — VOLVO Construction Logistics Asset Fleets",
    category: "Oil Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["VOLVO Construction Logistics Asset Fleets"],
    notes: "OEM: 421-06-35111 · Supplier: Kafu",
  },
  {
    id: "kafu-a04-18f",
    partNumber: "A04-18F",
    partNumbers: ["A04-18F", "459-2591"],
    name: "Oil Pressure Sensor — CATERPILLAR Heavy Infrastructure Equipment",
    category: "Oil Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Heavy Infrastructure Equipment"],
    notes: "OEM: 459-2591 · Supplier: Kafu",
  },
  {
    id: "kafu-a04-18g",
    partNumber: "A04-18G",
    partNumbers: ["A04-18G", "304-5666"],
    name: "Oil Pressure Sensor — CATERPILLAR Logistics Fleet Engine Grids",
    category: "Oil Pressure Sensor",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Logistics Fleet Engine Grids"],
    notes: "OEM: 304-5666 · Supplier: Kafu",
  },
  {
    id: "kafu-a04-19",
    partNumber: "A04-19",
    partNumbers: ["A04-19", "3E-6455"],
    name: "Oil Pressure Switch — CATERPILLAR E330B Heavy Excavator Systems",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR E330B Heavy Excavator Systems"],
    notes: "OEM: 3E-6455 · Supplier: Kafu",
  },
  {
    id: "kafu-a04-19a",
    partNumber: "A04-19A",
    partNumbers: ["A04-19A", "107-0612"],
    name: "Oil Pressure Switch — CATERPILLAR General Field Operations Assets",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR General Field Operations Assets"],
    notes: "OEM: 107-0612 · Supplier: Kafu",
  },
  {
    id: "kafu-a04-19b",
    partNumber: "A04-19B",
    partNumbers: ["A04-19B", "107-0613"],
    name: "Oil Pressure Switch — CATERPILLAR Fleet Power Generation Modules",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Fleet Power Generation Modules"],
    notes: "OEM: 107-0613 · Supplier: Kafu",
  },
  {
    id: "kafu-a04-19c",
    partNumber: "A04-19C",
    partNumbers: ["A04-19C", "9X4276"],
    name: "Oil Pressure Switch — CATERPILLAR Mining Fleet Logistics Platforms",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Mining Fleet Logistics Platforms"],
    notes: "OEM: 9X4276 · Supplier: Kafu",
  },
  {
    id: "kafu-a04-19d",
    partNumber: "A04-19D",
    partNumbers: ["A04-19D", "107-0611"],
    name: "Oil Pressure Switch — CATERPILLAR Earthmoving Equipment Core",
    category: "Oil Pressure Switch",
    quantity: 0,
    reorderAt: 0,
    cost: 0,
    price: 0,
    compatibility: ["CATERPILLAR Earthmoving Equipment Core"],
    notes: "OEM: 107-0611 · Supplier: Kafu",
  },
];

