/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChinaShipmentsRouteImport } from './routes/china-shipments'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LowStockRouteImport } from './routes/low-stock'
import { Route as ShareRouteImport } from './routes/share'
import { Route as ShareInboxRouteImport } from './routes/share-inbox'
import { Route as StockTakeRouteImport } from './routes/stock-take'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers.index'
import { Route as SuppliersSupplierIdRouteImport } from './routes/suppliers.$supplierId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinaShipmentsRoute = ChinaShipmentsRouteImport.update({
  id: '/china-shipments',
  path: '/china-shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LowStockRoute = LowStockRouteImport.update({
  id: '/low-stock',
  path: '/low-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareInboxRoute = ShareInboxRouteImport.update({
  id: '/share-inbox',
  path: '/share-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const StockTakeRoute = StockTakeRouteImport.update({
  id: '/stock-take',
  path: '/stock-take',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersSupplierIdRoute = SuppliersSupplierIdRouteImport.update({
  id: '/suppliers/$supplierId',
  path: '/suppliers/$supplierId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/china-shipments': typeof ChinaShipmentsRoute
  '/documents': typeof DocumentsRoute
  '/inventory': typeof InventoryRoute
  '/low-stock': typeof LowStockRoute
  '/share': typeof ShareRoute
  '/share-inbox': typeof ShareInboxRoute
  '/stock-take': typeof StockTakeRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/china-shipments': typeof ChinaShipmentsRoute
  '/documents': typeof DocumentsRoute
  '/inventory': typeof InventoryRoute
  '/low-stock': typeof LowStockRoute
  '/share': typeof ShareRoute
  '/share-inbox': typeof ShareInboxRoute
  '/stock-take': typeof StockTakeRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/clients': typeof ClientsIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/china-shipments': typeof ChinaShipmentsRoute
  '/documents': typeof DocumentsRoute
  '/inventory': typeof InventoryRoute
  '/low-stock': typeof LowStockRoute
  '/share': typeof ShareRoute
  '/share-inbox': typeof ShareInboxRoute
  '/stock-take': typeof StockTakeRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/china-shipments'
    | '/documents'
    | '/inventory'
    | '/low-stock'
    | '/share'
    | '/share-inbox'
    | '/stock-take'
    | '/clients/$clientId'
    | '/suppliers/$supplierId'
    | '/clients/'
    | '/suppliers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/china-shipments'
    | '/documents'
    | '/inventory'
    | '/low-stock'
    | '/share'
    | '/share-inbox'
    | '/stock-take'
    | '/clients/$clientId'
    | '/suppliers/$supplierId'
    | '/clients'
    | '/suppliers'
  id:
    | '__root__'
    | '/'
    | '/china-shipments'
    | '/documents'
    | '/inventory'
    | '/low-stock'
    | '/share'
    | '/share-inbox'
    | '/stock-take'
    | '/clients/$clientId'
    | '/suppliers/$supplierId'
    | '/clients/'
    | '/suppliers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChinaShipmentsRoute: typeof ChinaShipmentsRoute
  DocumentsRoute: typeof DocumentsRoute
  InventoryRoute: typeof InventoryRoute
  LowStockRoute: typeof LowStockRoute
  ShareRoute: typeof ShareRoute
  ShareInboxRoute: typeof ShareInboxRoute
  StockTakeRoute: typeof StockTakeRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  SuppliersSupplierIdRoute: typeof SuppliersSupplierIdRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/china-shipments': {
      id: '/china-shipments'
      path: '/china-shipments'
      fullPath: '/china-shipments'
      preLoaderRoute: typeof ChinaShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/low-stock': {
      id: '/low-stock'
      path: '/low-stock'
      fullPath: '/low-stock'
      preLoaderRoute: typeof LowStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-inbox': {
      id: '/share-inbox'
      path: '/share-inbox'
      fullPath: '/share-inbox'
      preLoaderRoute: typeof ShareInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-take': {
      id: '/stock-take'
      path: '/stock-take'
      fullPath: '/stock-take'
      preLoaderRoute: typeof StockTakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$supplierId': {
      id: '/suppliers/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof SuppliersSupplierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChinaShipmentsRoute: ChinaShipmentsRoute,
  DocumentsRoute: DocumentsRoute,
  InventoryRoute: InventoryRoute,
  LowStockRoute: LowStockRoute,
  ShareRoute: ShareRoute,
  ShareInboxRoute: ShareInboxRoute,
  StockTakeRoute: StockTakeRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  SuppliersSupplierIdRoute: SuppliersSupplierIdRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
